export const INDONESIAN_UI_EXACT: Record<string, string> = {
  'MANAGE': 'KELOLA',
  'ASSURE': 'PENJAMINAN',
  'MONITOR': 'PANTAU',
  'Define & govern': 'Definisikan & tata kelola',
  'Assess & validate': 'Asesmen & validasi',
  'Monitor & respond': 'Pantau & tindak lanjuti',

  'Core Dashboard': 'Dasbor Utama',
  'Institution Onboarding': 'Pendaftaran Institusi',
  'Organization Structure': 'Struktur Organisasi',
  'User & Role Management': 'Manajemen Pengguna & Peran',
  'Authentication Security': 'Keamanan Autentikasi',
  'Data Integration Hub': 'Pusat Integrasi Data',
  'Process Architecture (BPM)': 'Arsitektur Proses (BPM)',
  'Risk Universe & Heatmap': 'Semesta Risiko & Heatmap',
  'Single Control Library': 'Pustaka Kontrol Tunggal',
  'Relational RCM Workspace': 'Ruang Kerja RCM Relasional',
  'Enterprise Evidence Repository': 'Repositori Bukti Perusahaan',
  'RCSA & CSA Workspace': 'Ruang Kerja RCSA & CSA',
  'ICOFR Program Hub': 'Pusat Program ICOFR',
  'ICOFR Scoping & Materiality': 'Ruang Lingkup & Materialitas ICOFR',
  'Accounts, Disclosures & Assertions': 'Akun, Pengungkapan & Asersi',
  'ICOFR Traceability Matrix': 'Matriks Ketertelusuran ICOFR',
  'ICOFR Coverage & Gap Analytics': 'Analitik Cakupan & Kesenjangan ICOFR',
  'Entity-Level Controls (ELC)': 'Kontrol Tingkat Entitas (ELC)',
  'Process-Level Controls (PLC)': 'Kontrol Tingkat Proses (PLC)',
  'IT General Controls (ITGC)': 'Kontrol Umum TI (ITGC)',
  'IT Application Controls (ITAC)': 'Kontrol Aplikasi TI (ITAC)',
  'IPE & EUC Register': 'Register IPE & EUC',
  'ICOFR Testing Plan & Cycle': 'Rencana & Siklus Pengujian ICOFR',
  'ICOFR Smart Testing Strategy': 'Strategi Pengujian Cerdas ICOFR',
  'ICOFR Sampling & Evidence': 'Sampling & Bukti ICOFR',
  'ICOFR Workpaper Review': 'Review Kertas Kerja ICOFR',
  'Walkthrough & ToD': 'Walkthrough & ToD',
  'ToE Testing & Samples': 'Pengujian ToE & Sampel',
  'ICOFR Deficiency Evaluation': 'Evaluasi Defisiensi ICOFR',
  'Remediation & MAP': 'Remediasi & MAP',
  'Control Health Cockpit': 'Kokpit Kesehatan Kontrol',
  'Continuous Monitoring (CCM)': 'Pemantauan Berkelanjutan (CCM)',
  'ICOFR Certification & Close': 'Sertifikasi & Penutupan ICOFR',
  'ICOFR Executive Reporting': 'Pelaporan Eksekutif ICOFR',
  'ICOFR Period Close & Archive': 'Penutupan Periode & Arsip ICOFR',
  'ICOFR Roll-Forward': 'Peralihan Periode ICOFR',
  'Assurance Calendar': 'Kalender Penjaminan',
  'Task Center & Escalation': 'Pusat Tugas & Eskalasi',
  'Analytics': 'Analitik',

  'Home': 'Beranda',
  'Process': 'Proses',
  'Processes': 'Proses',
  'Controls': 'Kontrol',
  'Tasks': 'Tugas',
  'Reports': 'Laporan',
  'More': 'Lainnya',
  'Profile': 'Profil',
  'My profile': 'Profil Saya',
  'Sign out': 'Keluar',
  'Sign In': 'Masuk',
  'Sign in': 'Masuk',
  'Sign in to Total ARC': 'Masuk ke Total ARC',
  'Signing in…': 'Sedang masuk…',
  'Show password': 'Tampilkan kata sandi',
  'Hide password': 'Sembunyikan kata sandi',
  'Password': 'Kata Sandi',
  'Total ARC Secure Access': 'Akses Aman Total ARC',
  'About Total ARC': 'Tentang Total ARC',
  'Integrated Modules': 'Modul Terintegrasi',
  'Connected Workflow': 'Alur Kerja Terhubung',
  'Actionable Reporting': 'Pelaporan yang Dapat Ditindaklanjuti',
  'Business Value': 'Nilai Bisnis',
  'Overview': 'Ringkasan',

  'Institution': 'Institusi',
  'Active institution': 'Institusi aktif',
  'Select institution': 'Pilih institusi',
  'Select active institution': 'Pilih institusi aktif',
  'Open navigation': 'Buka navigasi',
  'Close navigation': 'Tutup navigasi',
  'Total ARC home': 'Beranda Total ARC',

  'Create': 'Buat',
  'Add': 'Tambah',
  'Update': 'Perbarui',
  'Edit': 'Ubah',
  'Delete': 'Hapus',
  'Remove': 'Hapus',
  'Save': 'Simpan',
  'Cancel': 'Batal',
  'Close': 'Tutup',
  'Back': 'Kembali',
  'Next': 'Berikutnya',
  'Previous': 'Sebelumnya',
  'Continue': 'Lanjutkan',
  'Confirm': 'Konfirmasi',
  'Submit': 'Kirim',
  'Approve': 'Setujui',
  'Reject': 'Tolak',
  'Validate': 'Validasi',
  'Review': 'Review',
  'View': 'Lihat',
  'Download': 'Unduh',
  'Upload': 'Unggah',
  'Export': 'Ekspor',
  'Import': 'Impor',
  'Refresh': 'Muat Ulang',
  'Search': 'Cari',
  'Filter': 'Saring',
  'Clear': 'Bersihkan',
  'Reset': 'Atur Ulang',
  'Apply': 'Terapkan',
  'Actions': 'Aksi',
  'Action': 'Aksi',
  'Details': 'Detail',
  'Summary': 'Ringkasan',
  'History': 'Riwayat',
  'Settings': 'Pengaturan',
  'Status': 'Status',
  'Type': 'Jenis',
  'Name': 'Nama',
  'Title': 'Judul',
  'Description': 'Deskripsi',
  'Category': 'Kategori',
  'Owner': 'Pemilik',
  'Date': 'Tanggal',
  'Created At': 'Dibuat Pada',
  'Updated At': 'Diperbarui Pada',
  'Created By': 'Dibuat Oleh',
  'Updated By': 'Diperbarui Oleh',
  'Source': 'Sumber',
  'Evidence': 'Bukti',
  'Notes': 'Catatan',
  'Comment': 'Komentar',
  'Comments': 'Komentar',
  'Reason': 'Alasan',
  'Priority': 'Prioritas',
  'Frequency': 'Frekuensi',
  'Nature': 'Sifat',
  'System': 'Sistem',
  'Performer': 'Pelaksana',
  'Objective': 'Tujuan',
  'Objectives': 'Tujuan',
  'Criticality': 'Kritikalitas',
  'Classification': 'Klasifikasi',
  'Relevant': 'Relevan',
  'Required': 'Wajib',
  'Optional': 'Opsional',
  'Yes': 'Ya',
  'No': 'Tidak',

  'Loading': 'Memuat',
  'Loading…': 'Memuat…',
  'Loading...': 'Memuat...',
  'Saving…': 'Menyimpan…',
  'Saving...': 'Menyimpan...',
  'Processing…': 'Memproses…',
  'Processing...': 'Memproses...',
  'Generating…': 'Membuat…',
  'Generating...': 'Membuat...',
  'Analyzing…': 'Menganalisis…',
  'Analyzing...': 'Menganalisis...',
  'No data': 'Tidak ada data',
  'No data available': 'Data tidak tersedia',
  'No records found': 'Tidak ada data ditemukan',
  'Not provided': 'Belum tersedia',
  'Not Provided': 'Belum tersedia',
  'Not available': 'Tidak tersedia',
  'Not Available': 'Tidak tersedia',
  'Not assessed': 'Belum dinilai',
  'Not Assessed': 'Belum dinilai',
  'Pending': 'Menunggu',
  'Pending Validation': 'Menunggu Validasi',
  'Pending User Validation': 'Menunggu Validasi Pengguna',
  'Draft': 'Draf',
  'Active': 'Aktif',
  'Inactive': 'Tidak Aktif',
  'Approved': 'Disetujui',
  'Rejected': 'Ditolak',
  'Completed': 'Selesai',
  'Closed': 'Ditutup',
  'Open': 'Terbuka',
  'In Progress': 'Sedang Berjalan',
  'High': 'Tinggi',
  'Medium': 'Sedang',
  'Low': 'Rendah',
  'Critical': 'Kritis',
  'Effective': 'Efektif',
  'Ineffective': 'Tidak Efektif',
  'Pass': 'Lulus',
  'Fail': 'Gagal',
  'Passed': 'Lulus',
  'Failed': 'Gagal',

  'Business Process': 'Proses Bisnis',
  'Business Processes': 'Proses Bisnis',
  'Process Name': 'Nama Proses',
  'Process Name *': 'Nama Proses *',
  'Process ID': 'ID Proses',
  'Process Owner': 'Pemilik Proses',
  'Process Objective': 'Tujuan Proses',
  'Process Objectives': 'Tujuan Proses',
  'Update Business Process': 'Perbarui Proses Bisnis',
  'Create Business Process': 'Buat Proses Bisnis',
  'Update Process Master': 'Perbarui Master Proses',
  'Activity Register': 'Register Aktivitas',
  'ACTIVITY REGISTER': 'REGISTER AKTIVITAS',
  'Flow Process Diagram': 'Diagram Alur Proses',
  'Saved versions': 'Versi tersimpan',
  'Generate & Save': 'Buat & Simpan',
  'Generate & Save Flow': 'Buat & Simpan Alur',
  'Regenerate': 'Buat Ulang',
  'Set Active': 'Jadikan Aktif',
  'View Fullscreen': 'Lihat Layar Penuh',
  'Supporting Document & AI Process Definition': 'Dokumen Pendukung & Definisi Proses AI',
  'Upload & Analyze': 'Unggah & Analisis',
  'AI BPM Draft': 'Draf BPM AI',
  'AI Flowchart Preview': 'Pratinjau Flowchart AI',
  'Use Master Suggestions': 'Gunakan Usulan Master',
  'Reject Draft': 'Tolak Draf',
  'Validate & Apply BPM': 'Validasi & Terapkan BPM',
  'Supporting document history': 'Riwayat dokumen pendukung',
  'Source gaps': 'Kesenjangan sumber',
  'AI assumptions to validate': 'Asumsi AI yang perlu divalidasi',

  'Risk': 'Risiko',
  'Risks': 'Risiko',
  'Risk Register': 'Register Risiko',
  'Risk Universe': 'Semesta Risiko',
  'Risk Universe (Manage)': 'Semesta Risiko (Kelola)',
  'RISK UNIVERSE (MANAGE)': 'SEMESTA RISIKO (KELOLA)',
  'Enterprise Risk Register & Heatmaps': 'Register Risiko Perusahaan & Heatmap',
  'Identify New Risk': 'Identifikasi Risiko Baru',
  'AI Create Risk Register': 'AI Buat Register Risiko',
  'Create Risk Register from Business Process': 'Buat Register Risiko dari Proses Bisnis',
  'Select Business Process': 'Pilih Proses Bisnis',
  'Selected BPM': 'BPM Terpilih',
  'Generate Relevant Risk Types': 'Buat Jenis Risiko yang Relevan',
  'Generate AI Risks': 'Buat Risiko dengan AI',
  'Select Risks to Create': 'Pilih Risiko yang Akan Dibuat',
  'Select all': 'Pilih semua',
  'Clear category': 'Bersihkan kategori',
  'Risk Owner': 'Pemilik Risiko',
  'Risk Owner *': 'Pemilik Risiko *',
  'Human assessment remains mandatory': 'Asesmen manusia tetap wajib',
  'Draft · Human Validation Required': 'Draf · Memerlukan Validasi Manusia',
  'Cause': 'Penyebab',
  'Event': 'Kejadian',
  'Impact': 'Dampak',
  'Why relevant': 'Alasan relevan',
  'BPM activity': 'Aktivitas BPM',
  'Operational': 'Operasional',
  'Financial Reporting': 'Pelaporan Keuangan',
  'Compliance': 'Kepatuhan',
  'Technology': 'Teknologi',
  'Cybersecurity': 'Keamanan Siber',
  'Strategic': 'Strategis',
  'Fraud': 'Fraud',
  'Third Party': 'Pihak Ketiga',
  'Inherent Risk': 'Risiko Inheren',
  'Residual Risk': 'Risiko Residual',
  'Inherent Likelihood': 'Kemungkinan Inheren',
  'Inherent Impact': 'Dampak Inheren',
  'Residual Likelihood': 'Kemungkinan Residual',
  'Residual Impact': 'Dampak Residual',
  'Inherent Rating': 'Peringkat Inheren',
  'Residual Rating': 'Peringkat Residual',
  'Risk Treatment': 'Perlakuan Risiko',
  '5×5 Inherent Heatmap': 'Heatmap Inheren 5×5',
  '5×5 Residual Heatmap': 'Heatmap Residual 5×5',
  'Select a risk from the register to inspect its 360° profile.': 'Pilih risiko dari register untuk melihat profil 360°.',

  'Control': 'Kontrol',
  'Control Library': 'Pustaka Kontrol',
  'Control Owner': 'Pemilik Kontrol',
  'Control Objective': 'Tujuan Kontrol',
  'Control Type': 'Jenis Kontrol',
  'Control Nature': 'Sifat Kontrol',
  'Control Frequency': 'Frekuensi Kontrol',
  'Design Effectiveness': 'Efektivitas Desain',
  'Operating Effectiveness': 'Efektivitas Operasional',
  'Key Control': 'Kontrol Kunci',
  'Non-Key Control': 'Kontrol Non-Kunci',

  'Management Action Plan': 'Rencana Tindak Lanjut Manajemen',
  'Issue': 'Isu',
  'Issues': 'Isu',
  'Deficiency': 'Defisiensi',
  'Deficiencies': 'Defisiensi',
  'Remediation': 'Remediasi',
  'Monitoring': 'Pemantauan',
  'Testing': 'Pengujian',
  'Test': 'Uji',
  'Sample': 'Sampel',
  'Samples': 'Sampel',
  'Testing Plan': 'Rencana Pengujian',
  'Workpaper': 'Kertas Kerja',
  'Workpaper Review': 'Review Kertas Kerja',
  'Certification': 'Sertifikasi',
  'Materiality': 'Materialitas',
  'Scope': 'Ruang Lingkup',
  'Scoping': 'Penetapan Ruang Lingkup',
  'Coverage': 'Cakupan',
  'Gap': 'Kesenjangan',
  'Gaps': 'Kesenjangan',
  'Account': 'Akun',
  'Accounts': 'Akun',
  'Disclosure': 'Pengungkapan',
  'Disclosures': 'Pengungkapan',
  'Assertion': 'Asersi',
  'Assertions': 'Asersi',

  'AI Analysis': 'Analisis AI',
  'AI Assistant': 'Asisten AI',
  'ARC AI': 'ARC AI',
  'Generate AI': 'Buat dengan AI',
  'Regenerate AI': 'Buat Ulang dengan AI',
  'AI Suggested': 'Usulan AI',
  'AI Suggested — User Selection & Human Assessment Required': 'Usulan AI — Memerlukan Pilihan Pengguna & Asesmen Manusia',
  'Reusable without AI': 'Dapat digunakan kembali tanpa AI',
  'Saved AI suggestion batches': 'Batch usulan AI tersimpan',
  'Saved · reusable without AI': 'Tersimpan · dapat digunakan kembali tanpa AI'
};

const REPLACERS: Array<[RegExp, (...args: string[]) => string]> = [
  [/^Risk Register \((\d+)\)$/i, (_all, n) => `Register Risiko (${n})`],
  [/^Version (\d+)$/i, (_all, n) => `Versi ${n}`],
  [/^Step (\d+)$/i, (_all, n) => `Langkah ${n}`],
  [/^(\d+) steps$/i, (_all, n) => `${n} langkah`],
  [/^(\d+) selected$/i, (_all, n) => `${n} dipilih`],
  [/^(\d+) available$/i, (_all, n) => `${n} tersedia`],
  [/^(\d+) proposed risks?$/i, (_all, n) => `${n} usulan risiko`],
  [/^Loading (.+)…$/i, (_all, subject) => `Memuat ${subject}…`],
  [/^Loading (.+)\.\.\.$/i, (_all, subject) => `Memuat ${subject}...`],
  [/^No (.+) found\.?$/i, (_all, subject) => `Tidak ada ${subject} ditemukan.`],
  [/^Select (.+) first\.?$/i, (_all, subject) => `Pilih ${subject} terlebih dahulu.`],
  [/^Select a (.+)$/i, (_all, subject) => `Pilih ${subject}`],
  [/^Search by (.+)$/i, (_all, subject) => `Cari berdasarkan ${subject}`],
  [/^Create (\d+) Selected Risks?$/i, (_all, n) => `Buat ${n} Risiko Terpilih`],
  [/^Created (.+)$/i, (_all, subject) => `Dibuat ${subject}`],
  [/^Updated (.+)$/i, (_all, subject) => `Diperbarui ${subject}`],
  [/^Unable to (.+)$/i, (_all, subject) => `Tidak dapat ${subject}`],
  [/^Failed to (.+)$/i, (_all, subject) => `Gagal ${subject}`],
  [/^(.+) is required\.?$/i, (_all, subject) => `${subject} wajib diisi.`],
  [/^(.+) was not found\.?$/i, (_all, subject) => `${subject} tidak ditemukan.`],
  [/^(.+) not found\.?$/i, (_all, subject) => `${subject} tidak ditemukan.`],
  [/^Pending (.+)$/i, (_all, subject) => `Menunggu ${subject}`]
];

export function translateUiToIndonesian(input: string) {
  const raw = String(input ?? '');
  const trimmed = raw.trim();
  if (!trimmed) return raw;

  const exact = INDONESIAN_UI_EXACT[trimmed];
  let translated = exact || trimmed;

  if (!exact) {
    for (const [pattern, replacer] of REPLACERS) {
      if (pattern.test(trimmed)) {
        translated = trimmed.replace(pattern, (...args) => replacer(...args.map(String)));
        break;
      }
    }
  }

  if (translated === trimmed) return raw;
  const start = raw.slice(0, raw.indexOf(trimmed));
  const end = raw.slice(raw.indexOf(trimmed) + trimmed.length);
  return start + translated + end;
}
