export const INDONESIAN_UI_EXACT: Record<string, string> = {
  'MANAGE': 'KELOLA',
  'ASSURE': 'PENJAMINAN',
  'MONITOR': 'PANTAU',
  'Define & govern': 'Definisikan & tata kelola',
  'Assess & validate': 'Asesmen & validasi',
  'Monitor & respond': 'Pantau & tindak lanjuti',

  'Core Dashboard': 'Dasbor Utama',
  'Institution Onboarding': 'Pendaftaran Institusi',
  'Organization Structure': 'Struktur Organisasi',
  'User & Role Management': 'Manajemen Pengguna & Peran',
  'Authentication Security': 'Keamanan Autentikasi',
  'Data Integration Hub': 'Pusat Integrasi Data',
  'Process Architecture (BPM)': 'Arsitektur Proses (BPM)',
  'Risk Universe & Heatmap': 'Semesta Risiko & Heatmap',
  'Single Control Library': 'Pustaka Kontrol Tunggal',
  'Relational RCM Workspace': 'Ruang Kerja RCM Relasional',
  'Enterprise Evidence Repository': 'Repositori Bukti Perusahaan',
  'RCSA & CSA Workspace': 'Ruang Kerja RCSA & CSA',
  'ICOFR Program Hub': 'Pusat Program ICOFR',
  'ICOFR Scoping & Materiality': 'Ruang Lingkup & Materialitas ICOFR',
  'Accounts, Disclosures & Assertions': 'Akun, Pengungkapan & Asersi',
  'ICOFR Traceability Matrix': 'Matriks Ketertelusuran ICOFR',
  'ICOFR Coverage & Gap Analytics': 'Analitik Cakupan & Kesenjangan ICOFR',
  'Entity-Level Controls (ELC)': 'Kontrol Tingkat Entitas (ELC)',
  'Process-Level Controls (PLC)': 'Kontrol Tingkat Proses (PLC)',
  'IT General Controls (ITGC)': 'Kontrol Umum TI (ITGC)',
  'IT Application Controls (ITAC)': 'Kontrol Aplikasi TI (ITAC)',
  'IPE & EUC Register': 'Register IPE & EUC',
  'ICOFR Testing Plan & Cycle': 'Rencana & Siklus Pengujian ICOFR',
  'ICOFR Smart Testing Strategy': 'Strategi Pengujian Cerdas ICOFR',
  'ICOFR Sampling & Evidence': 'Sampling & Bukti ICOFR',
  'ICOFR Workpaper Review': 'Review Kertas Kerja ICOFR',
  'Walkthrough & ToD': 'Walkthrough & ToD',
  'ToE Testing & Samples': 'Pengujian ToE & Sampel',
  'ICOFR Deficiency Evaluation': 'Evaluasi Defisiensi ICOFR',
  'Remediation & MAP': 'Remediasi & MAP',
  'Control Health Cockpit': 'Kokpit Kesehatan Kontrol',
  'Continuous Monitoring (CCM)': 'Pemantauan Berkelanjutan (CCM)',
  'ICOFR Certification & Close': 'Sertifikasi & Penutupan ICOFR',
  'ICOFR Executive Reporting': 'Pelaporan Eksekutif ICOFR',
  'ICOFR Period Close & Archive': 'Penutupan Periode & Arsip ICOFR',
  'ICOFR Roll-Forward': 'Peralihan Periode ICOFR',
  'Assurance Calendar': 'Kalender Penjaminan',
  'Task Center & Escalation': 'Pusat Tugas & Eskalasi',
  'Analytics': 'Analitik',

  'Home': 'Beranda',
  'Process': 'Proses',
  'Processes': 'Proses',
  'Controls': 'Kontrol',
  'Tasks': 'Tugas',
  'Reports': 'Laporan',
  'More': 'Lainnya',
  'Profile': 'Profil',
  'My profile': 'Profil Saya',
  'Sign out': 'Keluar',
  'Sign In': 'Masuk',
  'Sign in': 'Masuk',
  'Sign in to Total ARC': 'Masuk ke Total ARC',
  'Signing in…': 'Sedang masuk…',
  'Show password': 'Tampilkan kata sandi',
  'Hide password': 'Sembunyikan kata sandi',
  'Password': 'Kata Sandi',
  'Total ARC Secure Access': 'Akses Aman Total ARC',
  'About Total ARC': 'Tentang Total ARC',
  'Integrated Modules': 'Modul Terintegrasi',
  'Connected Workflow': 'Alur Kerja Terhubung',
  'Actionable Reporting': 'Pelaporan yang Dapat Ditindaklanjuti',
  'Business Value': 'Nilai Bisnis',
  'Overview': 'Ringkasan',

  'Institution': 'Institusi',
  'Active institution': 'Institusi aktif',
  'Select institution': 'Pilih institusi',
  'Select active institution': 'Pilih institusi aktif',
  'Open navigation': 'Buka navigasi',
  'Close navigation': 'Tutup navigasi',
  'Total ARC home': 'Beranda Total ARC',

  'Create': 'Buat',
  'Add': 'Tambah',
  'Update': 'Perbarui',
  'Edit': 'Ubah',
  'Delete': 'Hapus',
  'Remove': 'Hapus',
  'Save': 'Simpan',
  'Cancel': 'Batal',
  'Close': 'Tutup',
  'Back': 'Kembali',
  'Next': 'Berikutnya',
  'Previous': 'Sebelumnya',
  'Continue': 'Lanjutkan',
  'Confirm': 'Konfirmasi',
  'Submit': 'Kirim',
  'Approve': 'Setujui',
  'Reject': 'Tolak',
  'Validate': 'Validasi',
  'Review': 'Review',
  'View': 'Lihat',
  'Download': 'Unduh',
  'Upload': 'Unggah',
  'Export': 'Ekspor',
  'Import': 'Impor',
  'Refresh': 'Muat Ulang',
  'Search': 'Cari',
  'Filter': 'Saring',
  'Clear': 'Bersihkan',
  'Reset': 'Atur Ulang',
  'Apply': 'Terapkan',
  'Actions': 'Aksi',
  'Action': 'Aksi',
  'Details': 'Detail',
  'Summary': 'Ringkasan',
  'History': 'Riwayat',
  'Settings': 'Pengaturan',
  'Status': 'Status',
  'Type': 'Jenis',
  'Name': 'Nama',
  'Title': 'Judul',
  'Description': 'Deskripsi',
  'Category': 'Kategori',
  'Owner': 'Pemilik',
  'Date': 'Tanggal',
  'Created At': 'Dibuat Pada',
  'Updated At': 'Diperbarui Pada',
  'Created By': 'Dibuat Oleh',
  'Updated By': 'Diperbarui Oleh',
  'Source': 'Sumber',
  'Evidence': 'Bukti',
  'Notes': 'Catatan',
  'Comment': 'Komentar',
  'Comments': 'Komentar',
  'Reason': 'Alasan',
  'Priority': 'Prioritas',
  'Frequency': 'Frekuensi',
  'Nature': 'Sifat',
  'System': 'Sistem',
  'Performer': 'Pelaksana',
  'Objective': 'Tujuan',
  'Objectives': 'Tujuan',
  'Criticality': 'Kritikalitas',
  'Classification': 'Klasifikasi',
  'Relevant': 'Relevan',
  'Required': 'Wajib',
  'Optional': 'Opsional',
  'Yes': 'Ya',
  'No': 'Tidak',

  'Loading': 'Memuat',
  'Loading…': 'Memuat…',
  'Loading...': 'Memuat...',
  'Saving…': 'Menyimpan…',
  'Saving...': 'Menyimpan...',
  'Processing…': 'Memproses…',
  'Processing...': 'Memproses...',
  'Generating…': 'Membuat…',
  'Generating...': 'Membuat...',
  'Analyzing…': 'Menganalisis…',
  'Analyzing...': 'Menganalisis...',
  'No data': 'Tidak ada data',
  'No data available': 'Data tidak tersedia',
  'No records found': 'Tidak ada data ditemukan',
  'Not provided': 'Belum tersedia',
  'Not Provided': 'Belum tersedia',
  'Not available': 'Tidak tersedia',
  'Not Available': 'Tidak tersedia',
  'Not assessed': 'Belum dinilai',
  'Not Assessed': 'Belum dinilai',
  'Pending': 'Menunggu',
  'Pending Validation': 'Menunggu Validasi',
  'Pending User Validation': 'Menunggu Validasi Pengguna',
  'Draft': 'Draf',
  'Active': 'Aktif',
  'Inactive': 'Tidak Aktif',
  'Approved': 'Disetujui',
  'Rejected': 'Ditolak',
  'Completed': 'Selesai',
  'Closed': 'Ditutup',
  'Open': 'Terbuka',
  'In Progress': 'Sedang Berjalan',
  'High': 'Tinggi',
  'Medium': 'Sedang',
  'Low': 'Rendah',
  'Critical': 'Kritis',
  'Effective': 'Efektif',
  'Ineffective': 'Tidak Efektif',
  'Pass': 'Lulus',
  'Fail': 'Gagal',
  'Passed': 'Lulus',
  'Failed': 'Gagal',

  'Business Process': 'Proses Bisnis',
  'Business Processes': 'Proses Bisnis',
  'Process Name': 'Nama Proses',
  'Process Name *': 'Nama Proses *',
  'Process ID': 'ID Proses',
  'Process Owner': 'Pemilik Proses',
  'Process Objective': 'Tujuan Proses',
  'Process Objectives': 'Tujuan Proses',
  'Update Business Process': 'Perbarui Proses Bisnis',
  'Create Business Process': 'Buat Proses Bisnis',
  'Update Process Master': 'Perbarui Master Proses',
  'Activity Register': 'Register Aktivitas',
  'ACTIVITY REGISTER': 'REGISTER AKTIVITAS',
  'Flow Process Diagram': 'Diagram Alur Proses',
  'Saved versions': 'Versi tersimpan',
  'Generate & Save': 'Buat & Simpan',
  'Generate & Save Flow': 'Buat & Simpan Alur',
  'Regenerate': 'Buat Ulang',
  'Set Active': 'Jadikan Aktif',
  'View Fullscreen': 'Lihat Layar Penuh',
  'Supporting Document & AI Process Definition': 'Dokumen Pendukung & Definisi Proses AI',
  'Upload & Analyze': 'Unggah & Analisis',
  'AI BPM Draft': 'Draf BPM AI',
  'AI Flowchart Preview': 'Pratinjau Flowchart AI',
  'Use Master Suggestions': 'Gunakan Usulan Master',
  'Reject Draft': 'Tolak Draf',
  'Validate & Apply BPM': 'Validasi & Terapkan BPM',
  'Supporting document history': 'Riwayat dokumen pendukung',
  'Source gaps': 'Kesenjangan sumber',
  'AI assumptions to validate': 'Asumsi AI yang perlu divalidasi',

  'Risk': 'Risiko',
  'Risks': 'Risiko',
  'Risk Register': 'Register Risiko',
  'Risk Universe': 'Semesta Risiko',
  'Risk Universe (Manage)': 'Semesta Risiko (Kelola)',
  'RISK UNIVERSE (MANAGE)': 'SEMESTA RISIKO (KELOLA)',
  'Enterprise Risk Register & Heatmaps': 'Register Risiko Perusahaan & Heatmap',
  'Identify New Risk': 'Identifikasi Risiko Baru',
  'AI Create Risk Register': 'AI Buat Register Risiko',
  'Create Risk Register from Business Process': 'Buat Register Risiko dari Proses Bisnis',
  'Select Business Process': 'Pilih Proses Bisnis',
  'Selected BPM': 'BPM Terpilih',
  'Generate Relevant Risk Types': 'Buat Jenis Risiko yang Relevan',
  'Generate AI Risks': 'Buat Risiko dengan AI',
  'Select Risks to Create': 'Pilih Risiko yang Akan Dibuat',
  'Select all': 'Pilih semua',
  'Clear category': 'Bersihkan kategori',
  'Risk Owner': 'Pemilik Risiko',
  'Risk Owner *': 'Pemilik Risiko *',
  'Human assessment remains mandatory': 'Asesmen manusia tetap wajib',
  'Draft · Human Validation Required': 'Draf · Memerlukan Validasi Manusia',
  'Cause': 'Penyebab',
  'Event': 'Kejadian',
  'Impact': 'Dampak',
  'Why relevant': 'Alasan relevan',
  'BPM activity': 'Aktivitas BPM',
  'Operational': 'Operasional',
  'Financial Reporting': 'Pelaporan Keuangan',
  'Compliance': 'Kepatuhan',
  'Technology': 'Teknologi',
  'Cybersecurity': 'Keamanan Siber',
  'Strategic': 'Strategis',
  'Fraud': 'Fraud',
  'Third Party': 'Pihak Ketiga',
  'Inherent Risk': 'Risiko Inheren',
  'Residual Risk': 'Risiko Residual',
  'Inherent Likelihood': 'Kemungkinan Inheren',
  'Inherent Impact': 'Dampak Inheren',
  'Residual Likelihood': 'Kemungkinan Residual',
  'Residual Impact': 'Dampak Residual',
  'Inherent Rating': 'Peringkat Inheren',
  'Residual Rating': 'Peringkat Residual',
  'Risk Treatment': 'Perlakuan Risiko',
  '5×5 Inherent Heatmap': 'Heatmap Inheren 5×5',
  '5×5 Residual Heatmap': 'Heatmap Residual 5×5',
  'Select a risk from the register to inspect its 360° profile.': 'Pilih risiko dari register untuk melihat profil 360°.',

  'Control': 'Kontrol',
  'Control Library': 'Pustaka Kontrol',
  'Control Owner': 'Pemilik Kontrol',
  'Control Objective': 'Tujuan Kontrol',
  'Control Type': 'Jenis Kontrol',
  'Control Nature': 'Sifat Kontrol',
  'Control Frequency': 'Frekuensi Kontrol',
  'Design Effectiveness': 'Efektivitas Desain',
  'Operating Effectiveness': 'Efektivitas Operasional',
  'Key Control': 'Kontrol Kunci',
  'Non-Key Control': 'Kontrol Non-Kunci',

  'Management Action Plan': 'Rencana Tindak Lanjut Manajemen',
  'Issue': 'Isu',
  'Issues': 'Isu',
  'Deficiency': 'Defisiensi',
  'Deficiencies': 'Defisiensi',
  'Remediation': 'Remediasi',
  'Monitoring': 'Pemantauan',
  'Testing': 'Pengujian',
  'Test': 'Uji',
  'Sample': 'Sampel',
  'Samples': 'Sampel',
  'Testing Plan': 'Rencana Pengujian',
  'Workpaper': 'Kertas Kerja',
  'Workpaper Review': 'Review Kertas Kerja',
  'Certification': 'Sertifikasi',
  'Materiality': 'Materialitas',
  'Scope': 'Ruang Lingkup',
  'Scoping': 'Penetapan Ruang Lingkup',
  'Coverage': 'Cakupan',
  'Gap': 'Kesenjangan',
  'Gaps': 'Kesenjangan',
  'Account': 'Akun',
  'Accounts': 'Akun',
  'Disclosure': 'Pengungkapan',
  'Disclosures': 'Pengungkapan',
  'Assertion': 'Asersi',
  'Assertions': 'Asersi',

  'AI Analysis': 'Analisis AI',
  'AI Assistant': 'Asisten AI',
  'ARC AI': 'ARC AI',
  'Generate AI': 'Buat dengan AI',
  'Regenerate AI': 'Buat Ulang dengan AI',
  'AI Suggested': 'Usulan AI',
  'AI Suggested — User Selection & Human Assessment Required': 'Usulan AI — Memerlukan Pilihan Pengguna & Asesmen Manusia',
  'Reusable without AI': 'Dapat digunakan kembali tanpa AI',
  'Saved AI suggestion batches': 'Batch usulan AI tersimpan',
  'Saved · reusable without AI': 'Tersimpan · dapat digunakan kembali tanpa AI'
};


Object.assign(INDONESIAN_UI_EXACT, {
  'All types': 'Semua jenis',
  'All source roles': 'Semua peran sumber',
  'BASELINE': 'DATA DASAR',
  'UPDATE': 'PEMBARUAN',
  'Loading structured records…': 'Memuat data terstruktur…',
  'No records match the current filter.': 'Tidak ada data yang sesuai dengan filter saat ini.',
  'Show full structured payload': 'Tampilkan payload terstruktur lengkap',
  'Previous': 'Sebelumnya',
  'Next': 'Berikutnya',
  'records': 'data',
  'raw': 'mentah',
  'chars': 'karakter',
  'Reconciliation rows': 'Baris rekonsiliasi',
  'Aura baseline vs Seraya update classification': 'Klasifikasi data dasar Aura vs pembaruan Seraya',
  'Operational links': 'Tautan operasional',
  'source-backed links to Total ARC modules': 'tautan berbasis sumber ke modul Total ARC',
  'Governance exceptions': 'Pengecualian tata kelola',
  'review/config/policy items shown below': 'item review/konfigurasi/kebijakan ditampilkan di bawah',
  'Source precedence reconciliation': 'Rekonsiliasi prioritas sumber',
  'Method': 'Metode',
  'Confidence': 'Tingkat Keyakinan',
  'Baseline': 'Data Dasar',
  'Update': 'Pembaruan',
  'Module': 'Modul',
  'Open source-data conflicts': 'Konflik data sumber terbuka',
  'Seraya update': 'Pembaruan Seraya',
  'Other update source': 'Sumber pembaruan lain',
  'Mapping queue': 'Antrean pemetaan',
  'Operational-link policy': 'Kebijakan tautan operasional',
  'Items that must not be auto-promoted': 'Item yang tidak boleh dipromosikan otomatis',
  'Incomplete data': 'Data tidak lengkap',
  'Unidentified format': 'Format tidak teridentifikasi',
  'Review / mapping queue': 'Antrean review / pemetaan',
  'Open source data issues': 'Isu data sumber terbuka',
  'Observed': 'Teramati',
  'Expected / context': 'Ekspektasi / konteks',
  'Source exceptions & update candidates': 'Pengecualian sumber & kandidat pembaruan',
  'No source-level exceptions detected.': 'Tidak ada pengecualian tingkat sumber yang terdeteksi.',
  'Completeness by record type': 'Kelengkapan per jenis data',
  'Record type': 'Jenis data',
  'Total': 'Total',
  'Complete': 'Lengkap',
  'Partial': 'Parsial',
  'Incomplete': 'Tidak lengkap',
  'Unidentified': 'Tidak teridentifikasi',
  'key, title, source…': 'kunci, judul, sumber…',

  'Source account': 'Akun sumber',
  'Raw source': 'Sumber mentah',
  'Indexed text': 'Teks terindeks',
  'Sensitivity': 'Sensitivitas',
  'Indexed text belum tersedia': 'Teks terindeks belum tersedia',
  'Indexed source text': 'Teks sumber terindeks',
  'Provider:': 'Penyedia:',
  'Source kind:': 'Jenis sumber:',
  'Modified:': 'Diubah:',
  'External ID:': 'ID Eksternal:',

  'Authentication Sessions & Security Events': 'Sesi Autentikasi & Peristiwa Keamanan',
  'Password Governance': 'Tata Kelola Kata Sandi',
  'Length': 'Panjang',
  'Complexity': 'Kompleksitas',
  'Default/common password': 'Kata sandi default/umum',
  'Session Governance': 'Tata Kelola Sesi',
  'Absolute lifetime': 'Masa berlaku absolut',
  'Server revocation': 'Pencabutan server',
  'Activity checkpoint': 'Titik pemeriksaan aktivitas',
  'Role/password reset': 'Reset peran/kata sandi',
  'Revokes sessions': 'Mencabut sesi',
  'Active Session Register': 'Register Sesi Aktif',
  'Revoke a session after suspected misuse, offboarding, or access changes.': 'Cabut sesi setelah dugaan penyalahgunaan, offboarding, atau perubahan akses.',
  'User': 'Pengguna',
  'Role': 'Peran',
  'Issued': 'Diterbitkan',
  'Last Seen': 'Terakhir Terlihat',
  'Expires': 'Kedaluwarsa',
  'IP / Client': 'IP / Klien',
  'No active sessions.': 'Tidak ada sesi aktif.',
  'Security Event Log': 'Log Peristiwa Keamanan',
  'Latest 250 institution-scoped authentication and account events.': '250 peristiwa autentikasi dan akun terbaru pada institusi.',
  'All event types': 'Semua jenis peristiwa',
  'No events for this filter.': 'Tidak ada peristiwa untuk filter ini.',

  'User & Role Access Management': 'Manajemen Akses Pengguna & Peran',
  'One-time temporary password': 'Kata sandi sementara satu kali',
  'Create user': 'Buat pengguna',
  'Credential terpisah untuk setiap pengguna.': 'Kredensial terpisah untuk setiap pengguna.',
  'Full name': 'Nama lengkap',
  'Email / username': 'Email / nama pengguna',
  'Organization unit': 'Unit organisasi',
  'Not assigned': 'Belum ditetapkan',
  'Unit / department label': 'Label unit / departemen',
  'Initial password': 'Kata sandi awal',
  'Registered users': 'Pengguna terdaftar',
  'Belum ada user terdaftar.': 'Belum ada pengguna terdaftar.',
  'YOU': 'ANDA',
  'INACTIVE': 'TIDAK AKTIF',
  'LOCKED': 'TERKUNCI',
  'PASSWORD CHANGE': 'GANTI KATA SANDI',
  'Unlock user': 'Buka kunci pengguna',
  'Force password change': 'Wajibkan ganti kata sandi',
  'Reset credential': 'Reset kredensial',

  'No scheduled records': 'Tidak ada jadwal',
  '· Reviewer:': '· Reviewer:',
  'Refresh calendar': 'Muat ulang kalender',
  'Search schedule, owner, source, or status...': 'Cari jadwal, pemilik, sumber, atau status...',
  'Previous month': 'Bulan sebelumnya',
  'Next month': 'Bulan berikutnya',
  'Close schedule editor': 'Tutup editor jadwal',
  'Responsible owner': 'Pemilik yang bertanggung jawab',
  'Reviewer / approver': 'Reviewer / penyetuju',
  'Scope, dependency, evidence, or coordination notes': 'Catatan ruang lingkup, dependensi, bukti, atau koordinasi',

  'CCM Cockpit': 'Kokpit CCM',
  'No monitoring rules configured': 'Belum ada aturan pemantauan yang dikonfigurasi',
  'Data source': 'Sumber data',
  'Threshold': 'Ambang batas',
  'Configure CCM Rule': 'Konfigurasi Aturan CCM',
  'Control *': 'Kontrol *',
  'Rule ID': 'ID Aturan',
  'Frequency *': 'Frekuensi *',
  'Real Time': 'Waktu Nyata',
  'Hourly': 'Per Jam',
  'Daily': 'Harian',
  'Weekly': 'Mingguan',
  'Monthly': 'Bulanan',
  'Quarterly': 'Triwulanan',
  'Annual': 'Tahunan',
  'Rule Name *': 'Nama Aturan *',
  'Description *': 'Deskripsi *',
  'Data Source *': 'Sumber Data *',
  'Threshold *': 'Ambang Batas *',
  'Query / Detection Logic *': 'Kueri / Logika Deteksi *',
  'Auto-generated if blank': 'Dibuat otomatis jika kosong',
  'Enter monitoring rule name': 'Masukkan nama aturan pemantauan',
  'Describe the control condition that is continuously monitored': 'Jelaskan kondisi kontrol yang dipantau secara berkelanjutan',
  'ERP, API, DWH, SIEM, file feed...': 'ERP, API, DWH, SIEM, sumber file...',
  'e.g. 0 exceptions': 'contoh: 0 pengecualian',
  'Document the actual detection logic or query executed by the connected monitoring source': 'Dokumentasikan logika deteksi atau kueri aktual yang dijalankan oleh sumber pemantauan terhubung',

  'Management Certification, Readiness & Sign-Off': 'Sertifikasi Manajemen, Kesiapan & Persetujuan',
  'Scoping': 'Penetapan Ruang Lingkup',
  'Testing Plan': 'Rencana Pengujian',
  'Evidence Repository': 'Repositori Bukti',
  'Coverage & Gaps': 'Cakupan & Kesenjangan',
  '1. Entity / Unit Sub-Certification': '1. Sub-Sertifikasi Entitas / Unit',
  'Active form persisted to Cloudflare D1.': 'Form aktif disimpan di Cloudflare D1.',
  'Select scope': 'Pilih ruang lingkup',
  'No cycle linked': 'Tidak ada siklus tertaut',
  'Semi-Annual': 'Semesteran',
  'Year-End': 'Akhir Tahun',
  'Ad Hoc': 'Ad Hoc',
  'Legal Entity': 'Entitas Hukum',
  'Organization Unit': 'Unit Organisasi',
  'Select entity / unit': 'Pilih entitas / unit',
  'Not Concluded': 'Belum Disimpulkan',
  'Effective with Exceptions': 'Efektif dengan Pengecualian',
  'Under Review': 'Dalam Review',
  'Returned for Revision': 'Dikembalikan untuk Revisi',
  'Not reviewed': 'Belum direview',
  'Sub-Certification Register': 'Register Sub-Sertifikasi',
  'Entity/unit certifications roll up into the management attestation readiness view.': 'Sertifikasi entitas/unit dirangkum ke tampilan kesiapan atestasi manajemen.',
  '2. Management Attestation': '2. Atestasi Manajemen',
  'Management conclusion is explicitly entered; Total ARC does not infer it.': 'Kesimpulan manajemen diinput secara eksplisit; Total ARC tidak menyimpulkannya secara otomatis.',
  'Effective with Disclosed Exceptions': 'Efektif dengan Pengecualian yang Diungkapkan',
  'Ready for Sign-Off': 'Siap untuk Persetujuan',
  'Blocked': 'Diblokir',
  'Year-End Readiness Gate': 'Gerbang Kesiapan Akhir Tahun',
  'Select a saved attestation to evaluate persisted readiness evidence.': 'Pilih atestasi tersimpan untuk mengevaluasi bukti kesiapan.',
  'Select management attestation': 'Pilih atestasi manajemen',
  'Readiness override documented:': 'Override kesiapan terdokumentasi:',
  '3. Executive Sign-Off': '3. Persetujuan Eksekutif',
  'Records a named sign-off and readiness snapshot; it is not a cryptographic digital signature.': 'Mencatat persetujuan bernama dan snapshot kesiapan; bukan tanda tangan digital kriptografis.',
  '4. Year-End Evidence Pack': '4. Paket Bukti Akhir Tahun',
  'Registers actual evidence repository/file references; Total ARC does not fabricate attachments.': 'Mendaftarkan referensi repositori/file bukti aktual; Total ARC tidak membuat lampiran fiktif.',
  'Management Attestation & Evidence Register': 'Register Atestasi Manajemen & Bukti',
  'No management attestations registered.': 'Belum ada atestasi manajemen terdaftar.',
  'No year-end evidence packs registered.': 'Belum ada paket bukti akhir tahun terdaftar.',
  'Document review notes, conditions, required follow-up or approval rationale.': 'Dokumentasikan catatan review, kondisi, tindak lanjut yang diperlukan, atau alasan persetujuan.',
  'Describe the actual ICOFR perimeter covered by this management attestation.': 'Jelaskan perimeter ICOFR aktual yang dicakup atestasi manajemen ini.',
  'Enter the approved management representation wording.': 'Masukkan redaksi representasi manajemen yang telah disetujui.',
  'Disclose unresolved deficiencies or state the documented conclusion.': 'Ungkapkan defisiensi yang belum terselesaikan atau nyatakan kesimpulan terdokumentasi.',
  'Required documented override rationale.': 'Alasan override terdokumentasi wajib diisi.',
  'Document repository/path/reference ID': 'Repositori/path/ID referensi dokumen',

  'Single Control Library (MANAGE)': 'Pustaka Kontrol Tunggal (KELOLA)',
  'Register Control': 'Daftarkan Kontrol',
  'Control data unavailable.': 'Data kontrol tidak tersedia.',
  'Control 360°': 'Kontrol 360°',
  'Control profile unavailable.': 'Profil kontrol tidak tersedia.',
  'View in RCM': 'Lihat di RCM',
  'Method': 'Metode',
  'Frameworks:': 'Kerangka Kerja:',
  'Evidence Requirement:': 'Kebutuhan Bukti:',
  'Control Health 360° Assessment': 'Asesmen Kesehatan Kontrol 360°',
  'Design:': 'Desain:',
  'ToE records:': 'Data ToE:',
  'CCM:': 'CCM:',
  'Register Control Master': 'Daftarkan Master Kontrol',
  'Control ID': 'ID Kontrol',
  'Business Process *': 'Proses Bisnis *',
  'Register a business process first': 'Daftarkan proses bisnis terlebih dahulu',
  'Quick Related Risk': 'Risiko Terkait Cepat',
  'Risk Name *': 'Nama Risiko *',
  'Risk Category *': 'Kategori Risiko *',
  'Risk Event *': 'Kejadian Risiko *',
  'Impact *': 'Dampak *',
  'Impact Rating': 'Peringkat Dampak',
  'Control Name *': 'Nama Kontrol *',
  'Control Description *': 'Deskripsi Kontrol *',
  'Control Objective *': 'Tujuan Kontrol *',
  'Control Owner *': 'Pemilik Kontrol *',
  'Preventive': 'Preventif',
  'Detective': 'Detektif',
  'Corrective': 'Korektif',
  'Manual': 'Manual',
  'IT Dependent Manual': 'Manual Bergantung TI',
  'Automated': 'Otomatis',
  'Is Key Control?': 'Apakah Kontrol Kunci?',
  'ICOFR Key Control': 'Kontrol Kunci ICOFR',
  'Search Control ID, Name, Type, or Owner...': 'Cari ID Kontrol, Nama, Jenis, atau Pemilik...',
  'Describe the risk event': 'Jelaskan kejadian risiko',
  'Accountable risk owner': 'Pemilik risiko yang bertanggung jawab',
  'Primary cause or condition': 'Penyebab atau kondisi utama',
  'What could go wrong?': 'Apa yang dapat terjadi?',
  'Potential consequence': 'Konsekuensi potensial',
  'Describe control activities, criteria, and execution mechanism...': 'Jelaskan aktivitas kontrol, kriteria, dan mekanisme pelaksanaan...',
  'State the specific risk/control objective': 'Nyatakan tujuan risiko/kontrol yang spesifik',
  'Enter accountable control owner': 'Masukkan pemilik kontrol yang bertanggung jawab',

  'Sampling & Evidence': 'Sampling & Bukti',
  'PBC / Audit Reliance': 'PBC / Reliance Audit',
  'Identity control status:': 'Status kontrol identitas:',
  'Optional assurance link on upload': 'Tautan assurance opsional saat unggah',
  'No link now': 'Belum ditautkan',
  'Select target': 'Pilih target',
  'Evidence Register': 'Register Bukti',
  'Institution-scoped documents and current versions.': 'Dokumen per institusi dan versi terkini.',
  'Archived': 'Diarsipkan',
  'Legal Hold': 'Legal Hold',
  'All': 'Semua',
  'LEGAL HOLD': 'LEGAL HOLD',
  'Version History': 'Riwayat Versi',
  'CURRENT': 'TERKINI',
  'Governance Metadata': 'Metadata Tata Kelola',
  'Retention': 'Retensi',
  'Retention until': 'Retensi sampai',
  'Source system': 'Sistem sumber',
  'Assurance Traceability Links': 'Tautan Ketertelusuran Assurance',
  'Add link for current version': 'Tambah tautan untuk versi terkini',
  'Select type': 'Pilih jenis',
  'Evidence type *': 'Jenis bukti *',
  'Evidence owner *': 'Pemilik bukti *',
  'Persisted links': 'Tautan tersimpan',
  'Actual uploader name': 'Nama pengunggah aktual',

  'Loading integrated control evidence…': 'Memuat bukti kontrol terintegrasi…',
  'No controls registered': 'Belum ada kontrol terdaftar',
  'Register controls first; testing, assessment, monitoring, and issue evidence will then roll into this cockpit.': 'Daftarkan kontrol terlebih dahulu; bukti pengujian, asesmen, pemantauan, dan isu akan dirangkum ke kokpit ini.',
  'Operating:': 'Operasional:',
  'Issues:': 'Isu:',
  'Latest CCM:': 'CCM terbaru:',

  'ICOFR · Financial Statement Scoping': 'ICOFR · Ruang Lingkup Laporan Keuangan',
  'Significant Accounts, Disclosures & Assertions': 'Akun Signifikan, Pengungkapan & Asersi',
  'Register an institution before maintaining ICOFR accounts and disclosures.': 'Daftarkan institusi sebelum mengelola akun dan pengungkapan ICOFR.',
  'Assertions are recorded explicitly; no artificial defaults are inserted.': 'Asersi dicatat secara eksplisit; tidak ada default artifisial yang dimasukkan.',
  'New': 'Baru',
  'Record type *': 'Jenis data *',
  'Account': 'Akun',
  'Disclosure': 'Pengungkapan',
  'Code *': 'Kode *',
  'Account / disclosure name *': 'Nama akun / pengungkapan *',
  'Financial statement / note': 'Laporan keuangan / catatan',
  'Select': 'Pilih',
  'Statement of Financial Position': 'Laporan Posisi Keuangan',
  'Income Statement': 'Laporan Laba Rugi',
  'Cash Flow': 'Arus Kas',
  'Statement of Changes in Equity': 'Laporan Perubahan Ekuitas',
  'Notes / Disclosure': 'Catatan / Pengungkapan',
  'Regulatory Reporting': 'Pelaporan Regulasi',
  'Balance / exposure amount': 'Saldo / jumlah eksposur',
  'Currency': 'Mata uang',
  'Relevant assertions': 'Asersi relevan',
  'Significant / in-scope': 'Signifikan / dalam ruang lingkup',
  'Scoping rationale': 'Alasan penetapan ruang lingkup',
  'Financial reporting risk factors': 'Faktor risiko pelaporan keuangan',
  'Process / cycle reference': 'Referensi proses / siklus',
  'Out of Scope': 'Di Luar Ruang Lingkup',
  'Accounts & disclosures register': 'Register akun & pengungkapan',
  'No financial statement items registered.': 'Belum ada item laporan keuangan terdaftar.',
  'Significant': 'Signifikan',
  'Quantitative and qualitative rationale for inclusion/exclusion.': 'Alasan kuantitatif dan kualitatif untuk inklusi/eksklusi.',

  'Coverage, Gap & Action Management': 'Manajemen Cakupan, Kesenjangan & Tindakan',
  'ITAC → ITGC Dependency Mapping': 'Pemetaan Dependensi ITAC → ITGC',
  'Open ITAC': 'Buka ITAC',
  'Open ITGC': 'Buka ITGC',
  'Select ITAC': 'Pilih ITAC',
  'Select ITGC': 'Pilih ITGC',
  'ITGC Dependency': 'Dependensi ITGC',
  'Logical Access Dependency': 'Dependensi Akses Logis',
  'Change Management Dependency': 'Dependensi Manajemen Perubahan',
  'Computer Operations Dependency': 'Dependensi Operasi Komputer',
  'Interface / Batch Dependency': 'Dependensi Antarmuka / Batch',
  'SDLC Dependency': 'Dependensi SDLC',
  'Saved dependencies': 'Dependensi tersimpan',
  'Gap Action Form': 'Form Tindakan Kesenjangan',
  'Create or update an accountable action directly against an identified gap.': 'Buat atau perbarui tindakan yang bertanggung jawab langsung terhadap kesenjangan yang teridentifikasi.',
  'Create action': 'Buat tindakan',
  'Pending Review': 'Menunggu Review',
  'Cancelled': 'Dibatalkan',
  'Detected ICOFR gaps': 'Kesenjangan ICOFR terdeteksi',
  'All severity': 'Semua tingkat keparahan',
  'Calculating coverage and gaps…': 'Menghitung cakupan dan kesenjangan…',
  'ICOFR Gap Action Register': 'Register Tindakan Kesenjangan ICOFR',
  'Persistent accountable actions created from detected gaps.': 'Tindakan bertanggung jawab yang tersimpan dari kesenjangan terdeteksi.',
  'Gap': 'Kesenjangan',
  'Due Date': 'Tanggal Jatuh Tempo',
  'Explain why this ITGC supports reliable operation of the selected ITAC.': 'Jelaskan mengapa ITGC ini mendukung operasi ITAC terpilih secara andal.',
  'Remove dependency': 'Hapus dependensi',
  'State the concrete remediation or completion action.': 'Nyatakan tindakan remediasi atau penyelesaian yang konkret.',
  'Search gaps…': 'Cari kesenjangan…',

  'ICOFR · Deficiency Evaluation': 'ICOFR · Evaluasi Defisiensi',
  'Register an institution before maintaining ICOFR deficiencies.': 'Daftarkan institusi sebelum mengelola defisiensi ICOFR.',
  'Severity is a documented management/reviewer conclusion, not automatically inferred.': 'Tingkat keparahan merupakan kesimpulan manajemen/reviewer yang terdokumentasi, bukan hasil inferensi otomatis.',
  'Deficiency code *': 'Kode defisiensi *',
  'Title *': 'Judul *',
  'Control domain': 'Domain kontrol',
  'Control reference': 'Referensi kontrol',
  'Owner *': 'Pemilik *',
  'Deficiency description *': 'Deskripsi defisiensi *',
  'Financial statement impact': 'Dampak laporan keuangan',
  'Likelihood': 'Kemungkinan',
  'Remote': 'Rendah Kemungkinan',
  'Reasonably Possible': 'Cukup Mungkin',
  'Probable': 'Kemungkinan Besar',
  'Severity *': 'Tingkat Keparahan *',
  'Control Deficiency': 'Defisiensi Kontrol',
  'Significant Deficiency': 'Defisiensi Signifikan',
  'Material Weakness': 'Kelemahan Material',
  'Due date': 'Tanggal jatuh tempo',
  'Remediation In Progress': 'Remediasi Sedang Berjalan',
  'Pending Retest': 'Menunggu Pengujian Ulang',
  'Compensating controls': 'Kontrol kompensasi',
  'Management / reviewer conclusion': 'Kesimpulan manajemen / reviewer',
  'Aggregation with other deficiencies considered': 'Agregasi dengan defisiensi lain dipertimbangkan',
  'Deficiency register': 'Register defisiensi',
  'No ICOFR deficiencies registered.': 'Belum ada defisiensi ICOFR terdaftar.',
  'Affected accounts, disclosures, assertions, magnitude or possible misstatement.': 'Akun, pengungkapan, asersi, besaran, atau potensi salah saji yang terdampak.',

  'ICOFR · Information Reliability': 'ICOFR · Keandalan Informasi',
  'Register an institution before maintaining IPE/EUC.': 'Daftarkan institusi sebelum mengelola IPE/EUC.',
  'No sample records are preloaded.': 'Tidak ada data contoh yang dimuat sebelumnya.',
  'Type *': 'Jenis *',
  'Name *': 'Nama *',
  'Source system / tool': 'Sistem sumber / alat',
  'Purpose *': 'Tujuan *',
  'Data source': 'Sumber data',
  'Parameters / filters': 'Parameter / filter',
  'Validated': 'Divalidasi',
  'Retired': 'Dipensiunkan',
  'Logic / report generation description': 'Deskripsi logika / pembuatan laporan',
  'Completeness validation method': 'Metode validasi kelengkapan',
  'Accuracy validation method': 'Metode validasi akurasi',
  'Key report / key EUC': 'Laporan kunci / EUC kunci',
  'Access restricted': 'Akses dibatasi',
  'Version controlled': 'Versi dikendalikan',
  'IPE / EUC inventory': 'Inventaris IPE / EUC',
  'No IPE or EUC records registered.': 'Belum ada data IPE atau EUC terdaftar.',
  'Key': 'Kunci',

  'ICOFR controls': 'Kontrol ICOFR',
  'Accounts / disclosures': 'Akun / pengungkapan',
  'persistent financial items': 'item keuangan tersimpan',
  'Testing plan items': 'item rencana pengujian',
  'ToD / ToE annual cycle': 'siklus tahunan ToD / ToE',
  'Current scope': 'Ruang lingkup saat ini',

  'Period Locking, Versioning & Historical Evidence': 'Penguncian Periode, Versi & Bukti Historis',
  'Certification & Sign-Off': 'Sertifikasi & Persetujuan',
  'Executive Reporting': 'Pelaporan Eksekutif',
  '1. Close / Re-Close Period': '1. Tutup / Tutup Ulang Periode',
  'Select signed attestation': 'Pilih atestasi yang ditandatangani',
  'Prepared by *': 'Disiapkan oleh *',
  'Reviewer *': 'Reviewer *',
  'Approver *': 'Penyetuju *',
  'Closed Period Register': 'Register Periode Ditutup',
  'Each close retains historical snapshot versions and integrity hashes.': 'Setiap penutupan menyimpan versi snapshot historis dan hash integritas.',
  'No ICOFR periods have been closed.': 'Belum ada periode ICOFR yang ditutup.',
  '2. Controlled Reopen Request': '2. Permintaan Buka Ulang Terkendali',
  'Reopening is time-bound and cannot be self-approved.': 'Pembukaan ulang dibatasi waktu dan tidak dapat disetujui sendiri.',
  'Requested by *': 'Diminta oleh *',
  'Reason *': 'Alasan *',
  'Impact assessment *': 'Asesmen dampak *',
  'Requested reopen until *': 'Diminta dibuka ulang sampai *',
  'Submit reopen request': 'Kirim permintaan buka ulang',
  '3. Reopen Approval': '3. Persetujuan Buka Ulang',
  'Independent checker approval creates the temporary write window.': 'Persetujuan pemeriksa independen membuka jendela perubahan sementara.',
  'No pending reopen requests.': 'Tidak ada permintaan buka ulang yang menunggu.',
  'Reason:': 'Alasan:',
  'Impact:': 'Dampak:',
  'Decision': 'Keputusan',
  'Approved reopen until *': 'Disetujui buka ulang sampai *',
  'Approval comments': 'Komentar persetujuan',
  'Record decision': 'Catat keputusan',
  'Snapshot Integrity Register': 'Register Integritas Snapshot',
  'Section-level SHA-256 hashes make each historical snapshot independently verifiable.': 'Hash SHA-256 tingkat bagian membuat setiap snapshot historis dapat diverifikasi secara independen.',
  'No immutable snapshot records yet.': 'Belum ada data snapshot immutable.',
  'Version': 'Versi',
  'Section': 'Bagian',
  'Records': 'Data',
  'Created': 'Dibuat',
  'Describe records affected, financial-reporting impact and required retesting/re-certification.': 'Jelaskan data terdampak, dampak pelaporan keuangan, serta pengujian/sertifikasi ulang yang diperlukan.',

  'Board Reporting & External Audit Reliance': 'Pelaporan Dewan & Reliance Audit Eksternal',
  'Task Center': 'Pusat Tugas',
  'Deficiency Aging': 'Umur Defisiensi',
  'Audit & Close Snapshot': 'Snapshot Audit & Penutupan',
  'Signed attestations': 'Atestasi ditandatangani',
  'Issued report packs': 'Paket laporan diterbitkan',
  'Reliance mappings': 'Pemetaan reliance',
  'Accepted reliance': 'Reliance diterima',
  'Open PBC': 'PBC terbuka',
  'Open MAP': 'MAP terbuka',
  '1. Executive Report Pack Form': '1. Form Paket Laporan Eksekutif',
  'For Board, Audit Committee, management, regulator or external-auditor reporting.': 'Untuk pelaporan Dewan, Komite Audit, manajemen, regulator, atau auditor eksternal.',
  'Board of Directors': 'Dewan Direksi',
  'Audit Committee': 'Komite Audit',
  'Senior Management': 'Manajemen Senior',
  'External Auditor': 'Auditor Eksternal',
  'Regulator': 'Regulator',
  'No specific scope': 'Tidak ada ruang lingkup spesifik',
  'Issued': 'Diterbitkan',
  'Executive Report Pack Register': 'Register Paket Laporan Eksekutif',
  'No executive report packs registered.': 'Belum ada paket laporan eksekutif terdaftar.',
  '2. External Audit Reliance Mapping': '2. Pemetaan Reliance Audit Eksternal',
  'Links external-auditor reliance directly to an ICOFR control and its actual ToD/ToE evidence.': 'Menghubungkan reliance auditor eksternal langsung ke kontrol ICOFR dan bukti ToD/ToE aktual.',
  'Period *': 'Periode *',
  'External auditor *': 'Auditor eksternal *',
  'ICOFR control *': 'Kontrol ICOFR *',
  'Select control': 'Pilih kontrol',
  'Reliance area *': 'Area reliance *',
  'Control Design': 'Desain Kontrol',
  'Operating Effectiveness': 'Efektivitas Operasional',
  'Management Review Control': 'Kontrol Review Manajemen',
  'Planned reliance *': 'Reliance terencana *',
  'Planned Reliance': 'Reliance Terencana',
  'Potential Reliance': 'Potensi Reliance',
  'No Reliance': 'Tanpa Reliance',
  'To Be Determined': 'Akan Ditentukan',
  'Reliance conclusion': 'Kesimpulan reliance',
  'Rely': 'Mengandalkan',
  'Partial Reliance': 'Reliance Parsial',
  'Planning': 'Perencanaan',
  'Evidence Requested': 'Bukti Diminta',
  'Accepted for Reliance': 'Diterima untuk Reliance',
  'Reviewer': 'Reviewer',
  'Workpaper reference': 'Referensi kertas kerja',
  'Auditor reference': 'Referensi auditor',
  'External Audit Reliance Register': 'Register Reliance Audit Eksternal',
  'No reliance mappings registered.': 'Belum ada pemetaan reliance terdaftar.',
  '3. PBC / Evidence Request Tracker': '3. Pelacak Permintaan PBC / Bukti',
  'Open requests flow into Task Center with owner, priority, due date and direct source link.': 'Permintaan terbuka masuk ke Pusat Tugas dengan pemilik, prioritas, jatuh tempo, dan tautan sumber langsung.',
  'Request No. *': 'No. Permintaan *',
  'Category *': 'Kategori *',
  'Control Testing': 'Pengujian Kontrol',
  'Account / Assertion': 'Akun / Asersi',
  'Deficiency / MAP': 'Defisiensi / MAP',
  'Other': 'Lainnya',
  'Request description *': 'Deskripsi permintaan *',
  'Related record type': 'Jenis data terkait',
  'None / Other': 'Tidak Ada / Lainnya',
  'ICOFR Control': 'Kontrol ICOFR',
  'Attestation': 'Atestasi',
  'Evidence Pack': 'Paket Bukti',
  'Related record': 'Data terkait',
  'Request date *': 'Tanggal permintaan *',
  'Due date *': 'Tanggal jatuh tempo *',
  'Submitted': 'Dikirim',
  'Accepted': 'Diterima',
  'Evidence reference': 'Referensi bukti',
  'Response notes': 'Catatan respons',
  'PBC Request Register': 'Register Permintaan PBC',
  'No PBC requests registered.': 'Belum ada permintaan PBC terdaftar.',

  '1. Create New Period Baseline': '1. Buat Data Dasar Periode Baru',
  'Select closed period': 'Pilih periode yang ditutup',
  'Select version': 'Pilih versi',
  'Roll-Forward Register': 'Register Peralihan Periode',
  'Select a run to review year-over-year changes and carry-forward decisions.': 'Pilih run untuk mereview perubahan tahun-ke-tahun dan keputusan carry-forward.',
  '2. Year-over-Year Change Assessment': '2. Asesmen Perubahan Tahun-ke-Tahun',
  'All domains': 'Semua domain',
  'All deltas': 'Semua perubahan',
  'Unchanged': 'Tidak Berubah',
  'Changed': 'Berubah',
  'Missing / Retired': 'Hilang / Dipensiunkan',
  'Domain': 'Domain',
  'Code / Item': 'Kode / Item',
  'YoY delta': 'Perubahan YoY',
  'Changed fields': 'Field berubah',
  'System recommendation': 'Rekomendasi sistem',
  'Revalidation open': 'Revalidasi terbuka',
  'Carry Forward': 'Carry Forward',
  'Revalidate': 'Validasi Ulang',
  'Replace': 'Ganti',
  'Exclude': 'Kecualikan',
  'Carry Forward Follow-up': 'Tindak Lanjut Carry Forward',
  'Resolved / Closed': 'Terselesaikan / Ditutup',
  '3. Independent Final Review': '3. Review Final Independen',
  'Roll-forward finalized': 'Roll-forward difinalkan',
  'Search review items': 'Cari item review',
  'Document the current-period rationale, change assessment and any follow-up required.': 'Dokumentasikan alasan periode berjalan, asesmen perubahan, dan tindak lanjut yang diperlukan.',

  'Smart Testing Strategy': 'Strategi Pengujian Cerdas',
  'ToE Workpapers': 'Kertas Kerja ToE',
  'External Audit / PBC': 'Audit Eksternal / PBC',
  '1. Sampling Plan': '1. Rencana Sampling',
  'Population:': 'Populasi:',
  'Frequency:': 'Frekuensi:',
  'Phase:': 'Fase:',
  'Sampling Plan Register': 'Register Rencana Sampling',
  'Select a plan to manage population, evidence and ToE synchronization.': 'Pilih rencana untuk mengelola populasi, bukti, dan sinkronisasi ToE.',
  'candidates': 'kandidat',
  'selected': 'dipilih',
  'ToE linked': 'tertaut ToE',
  'failed': 'gagal',
  '2. Candidate Population Register': '2. Register Kandidat Populasi',
  'Register factual population references used for approved sample selection.': 'Daftarkan referensi populasi faktual yang digunakan untuk pemilihan sampel yang disetujui.',
  '3. Independent Approval & Selection': '3. Persetujuan & Pemilihan Independen',
  'Confirm population completeness before selection.': 'Konfirmasi kelengkapan populasi sebelum pemilihan.',
  'Reviewer:': 'Reviewer:',
  'Completeness basis:': 'Dasar kelengkapan:',
  '4. Population, Selection & Evidence Status': '4. Status Populasi, Pemilihan & Bukti',
  'Selected candidates retain the approved selection reason and their linked ToE sample result.': 'Kandidat terpilih menyimpan alasan pemilihan yang disetujui dan hasil sampel ToE terkait.',
  'Reference': 'Referensi',
  'Date / Amount': 'Tanggal / Jumlah',
  'Selection basis': 'Dasar pemilihan',
  'Evidence review': 'Review bukti',
  'ToE result': 'Hasil ToE',
  'Exception raised': 'Pengecualian dibuat',
  'Result': 'Hasil',
  '5. Evidence Completeness & Reviewer Sign-Off': '5. Kelengkapan Bukti & Persetujuan Reviewer',
  'Choose Evidence on a selected sample.': 'Pilih Bukti pada sampel terpilih.',
  'Save evidence review': 'Simpan review bukti',
  '6. Evidence / External Audit PBC Request': '6. Permintaan Bukti / PBC Audit Eksternal',
  'Internal Evidence Request': 'Permintaan Bukti Internal',
  'External Audit PBC': 'PBC Audit Eksternal',
  'Plan-level request': 'Permintaan tingkat rencana',
  'Request date *': 'Tanggal permintaan *',
  '7. Linked ToE Sample Result': '7. Hasil Sampel ToE Tertaut',
  'Choose Result on a ToE-linked sample.': 'Pilih Hasil pada sampel tertaut ToE.',
  'Not Tested': 'Belum Diuji',
  'Save ToE result': 'Simpan hasil ToE',
  '8. Complete Sampling & Evidence Work': '8. Selesaikan Sampling & Bukti',
  'evidence accepted': 'bukti diterima',
  'tested': 'diuji',
  'Sampling plan completed and retained in D1.': 'Rencana sampling selesai dan disimpan di D1.',
  'Evidence Request Register': 'Register Permintaan Bukti',
  'Request': 'Permintaan',
  'Blank = system recommendation': 'Kosong = rekomendasi sistem',
  'Blank = generated and persisted': 'Kosong = dibuat dan disimpan',
  'Approval evidence, segregation, authorization, accuracy, timeliness, configuration, etc.': 'Bukti persetujuan, segregasi, otorisasi, akurasi, ketepatan waktu, konfigurasi, dan lain-lain.',
  'Required only if the target sample size differs from the calculated recommendation.': 'Wajib hanya jika ukuran sampel target berbeda dari rekomendasi terhitung.',
  'Search candidate': 'Cari kandidat',
  'Completed by': 'Diselesaikan oleh',

  'Institution profile is required first': 'Profil institusi wajib tersedia terlebih dahulu',
  '1. Reporting perimeter': '1. Perimeter pelaporan',
  'Select period': 'Pilih periode',
  'Interim': 'Interim',
  'Special Purpose': 'Tujuan Khusus',
  'Select basis': 'Pilih basis',
  'Consolidated': 'Konsolidasian',
  'Standalone': 'Standalone',
  'Group + Components': 'Grup + Komponen',
  '2. Materiality': '2. Materialitas',
  'Select benchmark': 'Pilih benchmark',
  'Profit Before Tax': 'Laba Sebelum Pajak',
  'Revenue': 'Pendapatan',
  'Total Assets': 'Total Aset',
  'Equity': 'Ekuitas',
  'Operating Expenses': 'Beban Operasional',
  'Custom': 'Kustom',
  '3. In-scope coverage': '3. Cakupan dalam ruang lingkup',
  '4. Scoping criteria': '4. Kriteria ruang lingkup',
  'Select approach': 'Pilih pendekatan',
  'Risk-based': 'Berbasis Risiko',
  'Materiality + Risk-based': 'Materialitas + Berbasis Risiko',
  'Full Scope': 'Ruang Lingkup Penuh',
  'Top-down': 'Top-down',
  'Top-down risk-based': 'Top-down berbasis risiko',
  '5. Governance & approval': '5. Tata kelola & persetujuan',
  'Superseded': 'Digantikan',
  'Saved ICOFR scopes': 'Ruang lingkup ICOFR tersimpan',
  'FSLI in scope': 'FSLI dalam ruang lingkup',
  'incl. borderline': 'termasuk borderline',
  'Applications': 'Aplikasi',
  'revalidation applies': 'revalidasi berlaku',
  'Open source issues': 'Isu sumber terbuka',
  'not silently reconciled': 'tidak direkonsiliasi secara diam-diam',
  'Use benchmark × OM percentage': 'Gunakan benchmark × persentase OM',
  'Use OM × PM percentage': 'Gunakan OM × persentase PM',
  'Use PM × clearly trivial percentage': 'Gunakan PM × persentase clearly trivial',
  'Optional for group / component scoping': 'Opsional untuk ruang lingkup grup / komponen',
  'Document thresholds for significant accounts, balances, locations or components.': 'Dokumentasikan ambang batas akun, saldo, lokasi, atau komponen signifikan.',
  'Document deliberate exclusions and management rationale.': 'Dokumentasikan pengecualian yang disengaja dan alasan manajemen.',
  'Name / role': 'Nama / peran',

  'Roll-Forward': 'Peralihan Periode',
  '1. Generate Strategy Run': '1. Buat Run Strategi',
  'Select cycle': 'Pilih siklus',
  'No roll-forward context': 'Tidak ada konteks roll-forward',
  'Key Controls Only': 'Hanya Kontrol Kunci',
  'All Active ICOFR Controls': 'Semua Kontrol ICOFR Aktif',
  'Strategy Run Register': 'Register Run Strategi',
  'Select a run for reviewer decisions and plan integration.': 'Pilih run untuk keputusan reviewer dan integrasi rencana.',
  '2. Control-by-Control Testing Recommendation': '2. Rekomendasi Pengujian per Kontrol',
  'All strategies': 'Semua strategi',
  'Risk': 'Risiko',
  'Prior ToE': 'ToE Sebelumnya',
  'Exceptions / Deficiencies': 'Pengecualian / Defisiensi',
  'ITGC dependency': 'Dependensi ITGC',
  'Recommendation': 'Rekomendasi',
  'Evidence basis': 'Dasar bukti',
  'Accept Recommendation': 'Terima Rekomendasi',
  'Override': 'Override',
  'Defer': 'Tunda',
  '3. Approve & Apply to Testing Plan': '3. Setujui & Terapkan ke Rencana Pengujian',
  'Search controls': 'Cari kontrol',
  'Independent approver': 'Penyetuju independen',

  'Annual Testing Cycle & Execution Plan': 'Siklus Pengujian Tahunan & Rencana Pelaksanaan',
  'Scoping & Materiality': 'Ruang Lingkup & Materialitas',
  'Traceability': 'Ketertelusuran',
  'ToD Workspace': 'Ruang Kerja ToD',
  'ToE Workspace': 'Ruang Kerja ToE',
  'Certification': 'Sertifikasi',
  '1. Testing Cycle Form': '1. Form Siklus Pengujian',
  'Open Scoping & Materiality': 'Buka Ruang Lingkup & Materialitas',
  'Select strategy': 'Pilih strategi',
  'Annual Year-End': 'Tahunan Akhir Tahun',
  'Interim + Roll-Forward': 'Interim + Roll-Forward',
  'Quarterly Rotation': 'Rotasi Triwulanan',
  'Continuous / Staggered': 'Berkelanjutan / Bertahap',
  'Risk-Based Rotation': 'Rotasi Berbasis Risiko',
  'On Hold': 'Ditahan',
  'Saved Testing Cycles': 'Siklus Pengujian Tersimpan',
  'Select a cycle to manage its control-level testing plan.': 'Pilih siklus untuk mengelola rencana pengujian tingkat kontrol.',
  '2. Control Testing Plan Form': '2. Form Rencana Pengujian Kontrol',
  'Create or update one control-level annual testing assignment.': 'Buat atau perbarui satu penugasan pengujian tahunan tingkat kontrol.',
  'Select control': 'Pilih kontrol',
  'Both': 'Keduanya',
  'Select phase': 'Pilih fase',
  'Continuous': 'Berkelanjutan',
  'Select when ToE applies': 'Pilih saat ToE berlaku',
  'Random': 'Acak',
  'Systematic': 'Sistematis',
  'Judgmental': 'Berdasarkan Pertimbangan',
  'Risk-Based': 'Berbasis Risiko',
  'Full Population': 'Populasi Penuh',
  'Not specified': 'Belum ditentukan',
  'Management Testing': 'Pengujian Manajemen',
  'Internal Audit Reliance': 'Reliance Audit Internal',
  'External Audit Reliance': 'Reliance Audit Eksternal',
  'Combined Assurance': 'Assurance Gabungan',
  'No Reliance': 'Tanpa Reliance',
  'Planned': 'Direncanakan',
  'Deferred': 'Ditunda',
  '3. Bulk Plan Key Controls': '3. Rencana Massal Kontrol Kunci',
  'Testing Plan Register': 'Register Rencana Pengujian',
  'All cycles': 'Semua siklus',
  'Loading testing plan…': 'Memuat rencana pengujian…',
  'Plan': 'Rencana',
  'Schedule': 'Jadwal',
  'Assignment': 'Penugasan',
  'Population / Sample': 'Populasi / Sampel',
  'Carry-forward': 'Carry-forward',
  'Not planned': 'Belum direncanakan',
  'Continue ToD execution': 'Lanjutkan pelaksanaan ToD',
  'Review launched design workpapers and complete design criteria.': 'Review kertas kerja desain yang telah diluncurkan dan lengkapi kriteria desain.',
  'Continue ToE execution': 'Lanjutkan pelaksanaan ToE',
  'Add actual samples, evidence, results and exceptions to launched ToE workpapers.': 'Tambahkan sampel aktual, bukti, hasil, dan pengecualian ke kertas kerja ToE.',
  'Review coverage & gaps': 'Review cakupan & kesenjangan',
  'Validate whether key controls have the required ToD/ToE coverage and remediation actions.': 'Validasi apakah kontrol kunci memiliki cakupan ToD/ToE dan tindakan remediasi yang diperlukan.',
  'Required before ToE launch': 'Wajib sebelum ToE diluncurkan',
  'Actual source system/report/file; required before ToE launch': 'Sistem/laporan/file sumber aktual; wajib sebelum ToE diluncurkan',
  'Search control, tester, phase…': 'Cari kontrol, penguji, fase…',

  'End-to-End ICOFR Traceability Matrix': 'Matriks Ketertelusuran ICOFR End-to-End',
  '1. Build traceability chain': '1. Bangun rantai ketertelusuran',
  'Open Accounts & Assertions': 'Buka Akun & Asersi',
  'Open Risk Universe': 'Buka Semesta Risiko',
  'No enterprise control link yet': 'Belum ada tautan kontrol perusahaan',
  'No IPE/EUC dependency': 'Tidak ada dependensi IPE/EUC',
  '2. Register linked Test of Design': '2. Daftarkan Test of Design tertaut',
  'Partially Effective': 'Efektif Sebagian',
  'Traceability matrix': 'Matriks ketertelusuran',
  'Loading traceability…': 'Memuat ketertelusuran…',
  'Account / Disclosure': 'Akun / Pengungkapan',
  'ELC / PLC / ITGC / ITAC': 'ELC / PLC / ITGC / ITAC',
  'Deficiency': 'Defisiensi',
  'Document why the assertion is exposed to this risk and why the selected control addresses it.': 'Dokumentasikan mengapa asersi terekspos risiko ini dan mengapa kontrol terpilih mengatasinya.',
  'Search account, risk, control…': 'Cari akun, risiko, kontrol…',
  'Remove assertion-to-risk traceability link': 'Hapus tautan ketertelusuran asersi-ke-risiko',

  '1. Workpaper Preparation & Completeness': '1. Persiapan & Kelengkapan Kertas Kerja',
  'Select workpaper': 'Pilih kertas kerja',
  'Source status': 'Status sumber',
  'Source conclusion': 'Kesimpulan sumber',
  'Testing cycle': 'Siklus pengujian',
  'Workpaper Review Register': 'Register Review Kertas Kerja',
  'Open a review to manage evidence, review notes and final supervisory decision.': 'Buka review untuk mengelola bukti, catatan review, dan keputusan supervisi final.',
  'Quality gate': 'Gerbang kualitas',
  '2. Workpaper Evidence Index': '2. Indeks Bukti Kertas Kerja',
  'Reference supporting evidence; do not upload fake/sample evidence.': 'Referensikan bukti pendukung; jangan unggah bukti fiktif/contoh.',
  '3. Supervisory Review Notes': '3. Catatan Review Supervisi',
  'Open → Responded → Cleared/Waived. Unresolved notes block approval.': 'Terbuka → Direspons → Diselesaikan/Dikesampingkan. Catatan belum selesai memblokir persetujuan.',
  'Response:': 'Respons:',
  '4. Supervisory Decision': '4. Keputusan Supervisi',
  'Approved.': 'Disetujui.',
  'Return': 'Kembalikan',
  'Unresolved Review Point Dashboard': 'Dasbor Poin Review Belum Selesai',
  'Cross-workpaper supervisory review points still requiring response or clearance.': 'Poin review supervisi lintas kertas kerja yang masih memerlukan respons atau penyelesaian.',
  'Note': 'Catatan',
  'Workpaper': 'Kertas Kerja',
  'Report / screenshot / approval / configuration / reconciliation': 'Laporan / tangkapan layar / persetujuan / konfigurasi / rekonsiliasi',
  'System / repository / owner': 'Sistem / repositori / pemilik',

  'Institution Registration Wizard': 'Wizard Pendaftaran Institusi',
  'Province / State': 'Provinsi / Negara Bagian',
  'Select institution type': 'Pilih jenis institusi',
  'Stock Exchange & Ticker': 'Bursa & Ticker Saham',
  'Industry Group': 'Kelompok Industri',
  'Financial Services': 'Jasa Keuangan',
  'Energy': 'Energi',
  'Mining': 'Pertambangan',
  'Manufacturing': 'Manufaktur',
  'Telecommunications': 'Telekomunikasi',
  'Healthcare': 'Kesehatan',
  'Retail & Consumer': 'Ritel & Konsumen',
  'Sector': 'Sektor',
  'Subsector': 'Subsektor',
  'Business Model': 'Model Bisnis',
  'B2B (Business to Business)': 'B2B (Bisnis ke Bisnis)',
  'B2C (Business to Consumer)': 'B2C (Bisnis ke Konsumen)',
  'B2B2C (Hybrid Marketplace)': 'B2B2C (Marketplace Hibrida)',
  'B2G (Government Services)': 'B2G (Layanan Pemerintah)',
  'Operating Model': 'Model Operasi',
  'Centralized': 'Terpusat',
  'Decentralized': 'Terdesentralisasi',
  'Federated': 'Federasi',
  'Shared Service': 'Layanan Bersama',
  'Hybrid': 'Hibrida',
  'Employee Scale': 'Skala Karyawan',
  'Revenue Range': 'Rentang Pendapatan',
  'Institution Name:': 'Nama Institusi:',
  'Industry / Sector:': 'Industri / Sektor:',
  'Operating Model:': 'Model Operasi:',
  'Operational Seed Data:': 'Data Awal Operasional:',
  'None — real records only': 'Tidak ada — hanya data riil',

  'Institution registration is required first': 'Pendaftaran institusi wajib dilakukan terlebih dahulu',
  'Legal entities': 'Entitas hukum',
  'Org units': 'Unit organisasi',
  'Select level': 'Pilih level',
  'Institution level / not specified': 'Level institusi / belum ditentukan',
  'No parent — create top-level unit': 'Tanpa induk — buat unit tingkat atas',
  'Legal Entities': 'Entitas Hukum',
  'No legal entity yet': 'Belum ada entitas hukum',
  'Hierarchy Source Governance': 'Tata Kelola Sumber Hierarki',
  'Formal Branch Structure Reference': 'Referensi Struktur Cabang Formal',
  'Expanded Branch Structures': 'Struktur Cabang yang Diperluas',
  'Registered entity name': 'Nama entitas terdaftar',

  'Total ARC Command Center': 'Pusat Kendali Total ARC',
  'Live Assurance Snapshot': 'Snapshot Assurance Terkini',
  'Current control environment': 'Lingkungan kontrol saat ini',
  'ToE exceptions': 'Pengecualian ToE',
  'Failed / ineffective ToE': 'ToE gagal / tidak efektif',
  'Healthy CCM rules': 'Aturan CCM sehat',
  'Quick Access': 'Akses Cepat',
  'Key Metrics': 'Metrik Utama',
  'Core Modules': 'Modul Utama',
  'Recent Activity': 'Aktivitas Terbaru',
  'Executive Assurance Signals': 'Sinyal Assurance Eksekutif',
  'Data loaded': 'Data dimuat',

  'Process Architecture & BPM (MANAGE)': 'Arsitektur Proses & BPM (KELOLA)',
  'Draft / Not Assessed': 'Draf / Belum Dinilai',
  'AI Process Analysis': 'Analisis Proses AI',
  'Register Process': 'Daftarkan Proses',
  'Process data unavailable.': 'Data proses tidak tersedia.',
  'Inspect 360°': 'Lihat 360°',
  'Process profile unavailable.': 'Profil proses tidak tersedia.',
  'Hierarchy:': 'Hierarki:',
  'Source request:': 'Permintaan sumber:',
  'FY2026 source scope:': 'Ruang lingkup sumber FY2026:',
  'Validation gate:': 'Gerbang validasi:',
  'Validate & Apply': 'Validasi & Terapkan',
  'Mappings': 'Pemetaan',
  'Process Objectives & Target Metrics (Section 22)': 'Tujuan Proses & Metrik Target (Bagian 22)',
  'Core Objective:': 'Tujuan Utama:',
  'Target KPI:': 'KPI Target:',
  'Key Risk Indicator (KRI):': 'Indikator Risiko Utama (KRI):',
  'Supplier': 'Pemasok',
  'Input': 'Input',
  'Output': 'Output',
  'Customer': 'Pelanggan',
  'BPMN-Compatible Data': 'Data Kompatibel BPMN',
  'Category *': 'Kategori *',
  'Finance': 'Keuangan',
  'Governance': 'Tata Kelola',
  'Support': 'Pendukung',
  'Management': 'Manajemen',
  'ICOFR Relevant': 'Relevan ICOFR',
  'Supporting Document & ARC AI:': 'Dokumen Pendukung & ARC AI:',
  'Delete Business Process?': 'Hapus Proses Bisnis?',
  'Filter by Process ID, Name, or Owner...': 'Saring berdasarkan ID Proses, Nama, atau Pemilik...',
  'Delete Business Process': 'Hapus Proses Bisnis',
  'Leave blank if source/owner is not yet confirmed': 'Kosongkan jika sumber/pemilik belum dikonfirmasi',
  'Summarize process purpose, boundaries, and scope...': 'Ringkas tujuan, batasan, dan ruang lingkup proses...',

  'My Profile': 'Profil Saya',
  'Profile Information': 'Informasi Profil',
  'Email, role, institution and organization unit remain administrator-controlled.': 'Email, peran, institusi, dan unit organisasi tetap dikendalikan administrator.',
  'Change Password': 'Ganti Kata Sandi',
  'Password history and session revocation are enforced server-side.': 'Riwayat kata sandi dan pencabutan sesi diterapkan di sisi server.',
  'Current password': 'Kata sandi saat ini',
  'New password': 'Kata sandi baru',
  'Confirm new password': 'Konfirmasi kata sandi baru',

  'Dynamic RCM Workspace (MANAGE)': 'Ruang Kerja RCM Dinamis (KELOLA)',
  'Export RCM (CSV/Excel)': 'Ekspor RCM (CSV/Excel)',
  'Validation Queue': 'Antrean Validasi',
  'Risk:': 'Risiko:',
  'Control:': 'Kontrol:',
  'Update RCM Draft': 'Perbarui Draf RCM',
  'BPM Context': 'Konteks BPM',
  'Risk Draft': 'Draf Risiko',
  'Control Draft': 'Draf Kontrol',
  'Process (L2)': 'Proses (L2)',
  'Risk (Event & Impact)': 'Risiko (Kejadian & Dampak)',
  'Inherent Risk': 'Risiko Inheren',
  'Control Master': 'Master Kontrol',
  'Type & Nature': 'Jenis & Sifat',
  'ToE Testing': 'Pengujian ToE',
  'Residual': 'Residual',
  'Remediation / MAP': 'Remediasi / MAP',
  'Validated 1–5 assessment': 'Asesmen 1–5 tervalidasi',
  'No open issues': 'Tidak ada isu terbuka',
  'Testing:': 'Pengujian:',
  'Remediation:': 'Remediasi:',
  'Residual:': 'Residual:',
  'Close update draft': 'Tutup pembaruan draf',
  'Search process, risk, control, or control ID': 'Cari proses, risiko, kontrol, atau ID kontrol',

  'Loading persisted assessment data…': 'Memuat data asesmen tersimpan…',
  'No assessment campaign recorded': 'Belum ada kampanye asesmen tercatat',
  'Scope': 'Ruang Lingkup',
  'Campaign completion': 'Penyelesaian kampanye',
  'Best-practice setup': 'Pengaturan praktik terbaik',
  'Create RCSA / CSA Campaign': 'Buat Kampanye RCSA / CSA',
  'Combined': 'Gabungan',
  'Monthly': 'Bulanan',
  'Start date *': 'Tanggal mulai *',
  'COSO / ISO 31000 aligned': 'Selaras COSO / ISO 31000',
  'COSO Internal Control aligned': 'Selaras COSO Internal Control',
  'ISO 31000 aligned': 'Selaras ISO 31000',
  'Internal methodology': 'Metodologi internal',
  'Evidence reference mandatory before submission': 'Referensi bukti wajib sebelum pengiriman',
  'Select process': 'Pilih proses',
  'Risk (optional)': 'Risiko (opsional)',
  'Control (optional)': 'Kontrol (opsional)',
  'Add Assessment Scope': 'Tambah Ruang Lingkup Asesmen',
  'Select process *': 'Pilih proses *',
  'Risk & Control Self-Assessment': 'Asesmen Mandiri Risiko & Kontrol',
  'Design effectiveness *': 'Efektivitas desain *',
  'Operating effectiveness *': 'Efektivitas operasional *',
  'Evidence quality *': 'Kualitas bukti *',
  'Strong': 'Kuat',
  'Adequate': 'Memadai',
  'Limited': 'Terbatas',
  'None': 'Tidak Ada',
  'Confidence *': 'Tingkat keyakinan *',
  'Residual likelihood (1–5)': 'Kemungkinan residual (1–5)',
  'Residual impact (1–5)': 'Dampak residual (1–5)',
  'Overall conclusion *': 'Kesimpulan keseluruhan *',
  'Control performed as prescribed': 'Kontrol dilaksanakan sesuai ketentuan',
  'Exception / deviation identified': 'Pengecualian / deviasi teridentifikasi',
  'Remediation / follow-up action required': 'Remediasi / tindak lanjut diperlukan',
  'Independent review': 'Review independen',
  'Review Assessment': 'Review Asesmen',
  'Needs Revision': 'Perlu Revisi',
  'Refresh from database': 'Muat ulang dari database',
  'Campaign name *': 'Nama kampanye *',
  'Campaign code (auto if blank)': 'Kode kampanye (otomatis jika kosong)',
  'Assessment period *': 'Periode asesmen *',
  'Campaign owner *': 'Pemilik kampanye *',
  'Independent reviewer *': 'Reviewer independen *',
  'Assessment instructions': 'Instruksi asesmen',
  'Assessor / control owner': 'Asesor / pemilik kontrol',
  'Assessor / control owner *': 'Asesor / pemilik kontrol *',
  'Assessor *': 'Asesor *',
  'Evidence reference / document / ticket': 'Referensi bukti / dokumen / tiket',
  'Assessment rationale, evidence summary, observed gaps, and management response': 'Alasan asesmen, ringkasan bukti, kesenjangan teramati, dan respons manajemen',
  'Action owner *': 'Pemilik tindakan *',
  'Reviewer challenge, approval rationale, or revision instructions': 'Catatan challenge reviewer, alasan persetujuan, atau instruksi revisi',

  'No remediation lifecycle records': 'Belum ada data siklus remediasi',
  'Testing Exceptions': 'Pengecualian Pengujian',
  'No testing exceptions recorded.': 'Belum ada pengecualian pengujian tercatat.',
  'Control Deficiencies': 'Defisiensi Kontrol',
  'No human-approved deficiencies recorded.': 'Belum ada defisiensi yang disetujui manusia.',
  'No issues recorded.': 'Belum ada isu tercatat.',
  'Management Action Plans': 'Rencana Tindak Lanjut Manajemen',
  'No action plans recorded.': 'Belum ada rencana tindakan tercatat.',
  'Retest Records': 'Data Pengujian Ulang',
  'Deficiency Title *': 'Judul Defisiensi *',
  'Classification *': 'Klasifikasi *',
  'Observation': 'Observasi',
  'Financial Impact': 'Dampak Keuangan',
  'Approved By *': 'Disetujui Oleh *',
  'Regulatory Impact': 'Dampak Regulasi',
  'Compensating Controls': 'Kontrol Kompensasi',
  'Issue Title *': 'Judul Isu *',
  'Target Date *': 'Tanggal Target *',
  'Issue Owner *': 'Pemilik Isu *',
  'Agreed Action *': 'Tindakan yang Disepakati *',
  'Action Owner *': 'Pemilik Tindakan *',
  'Original Due Date *': 'Tanggal Jatuh Tempo Awal *',
  'Milestone *': 'Milestone *',
  'Samples *': 'Sampel *',
  'Passed *': 'Lulus *',
  'Failed *': 'Gagal *',
  'Tester *': 'Penguji *',
  'Conclusion Notes': 'Catatan Kesimpulan',
  'MAP Due-Date Extension': 'Perpanjangan Jatuh Tempo MAP',
  'Original Due Date': 'Tanggal Jatuh Tempo Awal',
  'New Due Date *': 'Tanggal Jatuh Tempo Baru *',
  'Extension Reason *': 'Alasan Perpanjangan *',
  'Approver Name *': 'Nama Penyetuju *',
  'Human approver': 'Penyetuju manusia',
  'Document the factual reason for the due-date extension': 'Dokumentasikan alasan faktual perpanjangan jatuh tempo',
  'Enter the approving person': 'Masukkan pihak yang menyetujui',

  'Report Source Center': 'Pusat Sumber Laporan',
  'Connected sources': 'Sumber terhubung',
  'Persisted records': 'Data tersimpan',
  'Open tasks': 'Tugas terbuka',
  'ICOFR Executive Reporting': 'Pelaporan Eksekutif ICOFR',
  'Board / Audit Committee & External Audit Reliance': 'Dewan / Komite Audit & Reliance Audit Eksternal',
  'Open the database-backed reporting pack, reliance mapping, deficiency aging and PBC tracker.': 'Buka paket pelaporan berbasis database, pemetaan reliance, umur defisiensi, dan pelacak PBC.',
  'Risk coverage': 'Cakupan risiko',
  'Residual assessment': 'Asesmen residual',
  'Key controls': 'Kontrol kunci',
  'Completed ToD + ToE': 'ToD + ToE selesai',
  'Regulatory mapping': 'Pemetaan regulasi',
  'Mapped controls': 'Kontrol terpetakan',
  'Loading connected report sources…': 'Memuat sumber laporan terhubung…',
  'persisted record(s)': 'data tersimpan',
  'Refresh report sources and AI analysis': 'Muat ulang sumber laporan dan analisis AI',

  'Risk data unavailable.': 'Data risiko tidak tersedia.',
  'Process:': 'Proses:',
  'Due to Penyebab:': 'Karena Penyebab:',
  'There is a Risk that (Kejadian):': 'Terdapat Risiko bahwa (Kejadian):',
  'Resulting in (Dampak):': 'Mengakibatkan (Dampak):',
  'Warning: No active control mapped to this risk. Control gap identified.': 'Peringatan: Tidak ada kontrol aktif yang dipetakan ke risiko ini. Kesenjangan kontrol teridentifikasi.',
  'Low 1–4': 'Rendah 1–4',
  'Medium 5–9': 'Sedang 5–9',
  'High 10–14': 'Tinggi 10–14',
  'Critical 15–25': 'Kritis 15–25',
  'Dampak 1 (Insignificant)': 'Dampak 1 (Tidak Signifikan)',
  'Dampak 5 (Catastrophic)': 'Dampak 5 (Katastropik)',
  'AI analysis unavailable.': 'Analisis AI tidak tersedia.',
  'Assessed': 'Sudah Dinilai',
  'Coverage': 'Cakupan',
  'Identifikasi Risiko Baru Master': 'Master Identifikasi Risiko Baru',
  'Kategori Risiko *': 'Kategori Risiko *',
  'Due to Penyebab: *': 'Karena Penyebab: *',
  'There is a Risk that (Kejadian): *': 'Terdapat Risiko bahwa (Kejadian): *',
  'Resulting in (Dampak): *': 'Mengakibatkan (Dampak): *',
  'Inherent Kemungkinan (1-5)': 'Kemungkinan Inheren (1-5)',
  'Inherent Dampak (1-5)': 'Dampak Inheren (1-5)',
  'Enter accountable risk owner': 'Masukkan pemilik risiko yang bertanggung jawab',

  'Assurance Tasks & Escalations': 'Tugas Assurance & Eskalasi',
  'Overdue': 'Terlambat',
  'Loading persisted tasks…': 'Memuat tugas tersimpan…',
  'No tasks in this view': 'Tidak ada tugas pada tampilan ini',
  'Tasks are created from operational assurance workflows rather than dummy records.': 'Tugas dibuat dari workflow assurance operasional, bukan data dummy.',
  'Open source →': 'Buka sumber →',
  'Refresh tasks': 'Muat ulang tugas',

  'Walkthrough & Test of Design': 'Walkthrough & Test of Design',
  'No ToD records yet': 'Belum ada data ToD',
  'Launch a ToD workpaper from the database-backed ICOFR Testing Plan.': 'Luncurkan kertas kerja ToD dari Rencana Pengujian ICOFR berbasis database.',
  'Open Testing Plan': 'Buka Rencana Pengujian',

  'Digital Testing Workpaper': 'Kertas Kerja Pengujian Digital',
  'No ToE tests recorded': 'Belum ada pengujian ToE tercatat',
  'Testing record': 'Data pengujian',
  'Failure reason': 'Alasan kegagalan',
  'Register ToE Test': 'Daftarkan Pengujian ToE',
  'Test ID': 'ID Pengujian',
  'Period *': 'Periode *',
  'Population Size *': 'Ukuran Populasi *',
  'Sampling Method *': 'Metode Sampling *',
  'Population Source *': 'Sumber Populasi *',
  'Raise Testing Exception': 'Buat Pengecualian Pengujian',
  'Exception Description *': 'Deskripsi Pengecualian *',
  'Add Actual Test Sample': 'Tambah Sampel Pengujian Aktual',
  'Transaction / Sample Reference *': 'Referensi Transaksi / Sampel *',
  'Transaction Date *': 'Tanggal Transaksi *',
  'Amount': 'Jumlah',
  'Attributes to Test': 'Atribut yang Diuji',
  'Evidence Reference': 'Referensi Bukti',
  'Actual tester name': 'Nama penguji aktual',
  'Reviewer name, if assigned': 'Nama reviewer, jika ditetapkan',
  'Actual source system/report/file used as the population': 'Sistem/laporan/file sumber aktual yang digunakan sebagai populasi',
  'Scope or testing notes': 'Catatan ruang lingkup atau pengujian',
  'Describe the factual exception evidenced by this failed sample': 'Jelaskan pengecualian faktual yang dibuktikan oleh sampel gagal ini',
  'Source transaction or evidence reference': 'Referensi transaksi sumber atau bukti',
  'Document the actual attributes/criteria to test': 'Dokumentasikan atribut/kriteria aktual yang diuji',
  'Evidence repository/file reference': 'Referensi repositori/file bukti',

  'Traceability Chain': 'Rantai Ketertelusuran',
  'Register an institution before maintaining ICOFR controls.': 'Daftarkan institusi sebelum mengelola kontrol ICOFR.',
  'Persisted ICOFR control definition. Fields start blank by design.': 'Definisi kontrol ICOFR tersimpan. Field sengaja dimulai kosong.',
  'Event Driven': 'Dipicu Peristiwa',
  'Pending Validation': 'Menunggu Validasi',
  'ITDM-EUC': 'ITDM-EUC',
  'ITDM-IPE': 'ITDM-IPE',
  'MRC': 'MRC',
  'Preventive & Detective': 'Preventif & Detektif',
  'No Control Master link': 'Belum ada tautan Master Kontrol',
  'No process selected': 'Belum ada proses dipilih',
  'Cloudflare D1': 'Cloudflare D1',
  'Source-backed ITAC candidates': 'Kandidat ITAC berbasis sumber',
  'Describe what could cause a material misstatement or reporting failure.': 'Jelaskan apa yang dapat menyebabkan salah saji material atau kegagalan pelaporan.',
  'Existence, Completeness, Accuracy...': 'Eksistensi, Kelengkapan, Akurasi...',
  'COSO principle / internal framework': 'Prinsip COSO / kerangka internal',

  'Institution:': 'Institusi:',
  'Unit:': 'Unit:',
  'Open ARC AI': 'Buka ARC AI',
  'Open user account menu': 'Buka menu akun pengguna',
  'Close navigation': 'Tutup navigasi'
});

const REPLACERS: Array<[RegExp, (...args: string[]) => string]> = [
  [/^Risk Register \((\d+)\)$/i, (_all, n) => `Register Risiko (${n})`],
  [/^Version (\d+)$/i, (_all, n) => `Versi ${n}`],
  [/^Step (\d+)$/i, (_all, n) => `Langkah ${n}`],
  [/^(\d+) steps$/i, (_all, n) => `${n} langkah`],
  [/^(\d+) selected$/i, (_all, n) => `${n} dipilih`],
  [/^(\d+) available$/i, (_all, n) => `${n} tersedia`],
  [/^(\d+) proposed risks?$/i, (_all, n) => `${n} usulan risiko`],
  [/^Loading (.+)…$/i, (_all, subject) => `Memuat ${subject}…`],
  [/^Loading (.+)\.\.\.$/i, (_all, subject) => `Memuat ${subject}...`],
  [/^No (.+) found\.?$/i, (_all, subject) => `Tidak ada ${subject} ditemukan.`],
  [/^Select (.+) first\.?$/i, (_all, subject) => `Pilih ${subject} terlebih dahulu.`],
  [/^Select a (.+)$/i, (_all, subject) => `Pilih ${subject}`],
  [/^Search by (.+)$/i, (_all, subject) => `Cari berdasarkan ${subject}`],
  [/^Create (\d+) Selected Risks?$/i, (_all, n) => `Buat ${n} Risiko Terpilih`],
  [/^Created (.+)$/i, (_all, subject) => `Dibuat ${subject}`],
  [/^Updated (.+)$/i, (_all, subject) => `Diperbarui ${subject}`],
  [/^Unable to (.+)$/i, (_all, subject) => `Tidak dapat ${subject}`],
  [/^Failed to (.+)$/i, (_all, subject) => `Gagal ${subject}`],
  [/^(.+) is required\.?$/i, (_all, subject) => `${subject} wajib diisi.`],
  [/^(.+) was not found\.?$/i, (_all, subject) => `${subject} tidak ditemukan.`],
  [/^(.+) not found\.?$/i, (_all, subject) => `${subject} tidak ditemukan.`],
  [/^Pending (.+)$/i, (_all, subject) => `Menunggu ${subject}`]
];

export function translateUiToIndonesian(input: string) {
  const raw = String(input ?? '');
  const trimmed = raw.trim();
  if (!trimmed) return raw;

  const exact = INDONESIAN_UI_EXACT[trimmed];
  let translated = exact || trimmed;

  if (!exact) {
    for (const [pattern, replacer] of REPLACERS) {
      if (pattern.test(trimmed)) {
        translated = trimmed.replace(pattern, (...args) => replacer(...args.map(String)));
        break;
      }
    }
  }

  if (translated === trimmed) return raw;
  const start = raw.slice(0, raw.indexOf(trimmed));
  const end = raw.slice(raw.indexOf(trimmed) + trimmed.length);
  return start + translated + end;
}
