'use client';

import React,{useEffect,useState} from 'react';
import { BadgeCheck } from 'lucide-react';

type Control={id:string;controlId:string;name:string}; type Cert={id:string;period:string;declarationText:string;certifierName:string;certifierRole:string;status:string;certifiedAt:string;control:Control}; type Att={id:string;period:string;scopeSummary:string;cfoSignOff:boolean;cfoName?:string|null;croSignOff:boolean;croName?:string|null;overallOpinion?:string|null;attestedAt?:string|null};

export default function CertificationPage(){
 const[certs,setCerts]=useState<Cert[]>([]);const[atts,setAtts]=useState<Att[]>([]);const[controls,setControls]=useState<Control[]>([]);const[message,setMessage]=useState('');
 const[certForm,setCertForm]=useState({controlId:'',period:'',declarationText:'',status:'Certified'});
 const[attForm,setAttForm]=useState({period:'',scopeSummary:'',overallOpinion:'',cfoSignOff:false,croSignOff:false,croName:''});
 const load=async()=>{const[a,b]=await Promise.all([fetch('/api/certification',{cache:'no-store'}),fetch('/api/controls',{cache:'no-store'})]);const ad=await a.json();const bd=await b.json();if(!a.ok)throw new Error(ad.error||'Unable to load certifications');setCerts(ad.certifications||[]);setAtts(ad.attestations||[]);setControls((bd.controls||[]).map((x:any)=>({id:x.id,controlId:x.controlId,name:x.name})));setCertForm(v=>({...v,controlId:v.controlId||bd.controls?.[0]?.id||''}));};
 useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
 const certify=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch('/api/certification',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'CERTIFY_CONTROL',...certForm})});const d=await r.json();if(!r.ok)return setMessage(d.error||'Unable to certify');setCertForm(v=>({...v,period:'',declarationText:''}));await load();};
 const attest=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch('/api/certification',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'ATTEST_MANAGEMENT',...attForm})});const d=await r.json();if(!r.ok)return setMessage(d.error||'Unable to attest');await load();};
 return <div className="space-y-6">
  <div><h1 className="text-xl font-black text-slate-900 flex items-center gap-2"><BadgeCheck className="w-5 h-5 text-brand-600"/>Certification & Attestation</h1><p className="text-xs text-slate-500 mt-1">Declarations are recorded by the authenticated actor and tied to live controls or institution periods.</p></div>
  {message&&<div className="text-xs text-slate-600 bg-slate-50 border border-slate-200 rounded-lg p-3">{message}</div>}
  <div className="grid xl:grid-cols-2 gap-5">
   <form onSubmit={certify} className="bg-white border border-slate-200 rounded-xl p-5 space-y-3 text-xs"><h2 className="text-sm font-bold text-slate-900">Control Certification</h2><label className="font-semibold text-slate-700 block">Control<select required value={certForm.controlId} onChange={e=>setCertForm({...certForm,controlId:e.target.value})} className="mt-1 w-full border border-slate-200 rounded-lg p-2.5 bg-white"><option value="">Select control</option>{controls.map(c=><option key={c.id} value={c.id}>{c.controlId} — {c.name}</option>)}</select></label><label className="font-semibold text-slate-700 block">Period<input required value={certForm.period} onChange={e=>setCertForm({...certForm,period:e.target.value})} className="mt-1 w-full border border-slate-200 rounded-lg p-2.5"/></label><label className="font-semibold text-slate-700 block">Declaration<textarea required value={certForm.declarationText} onChange={e=>setCertForm({...certForm,declarationText:e.target.value})} rows={5} className="mt-1 w-full border border-slate-200 rounded-lg p-2.5"/></label><label className="font-semibold text-slate-700 block">Status<select value={certForm.status} onChange={e=>setCertForm({...certForm,status:e.target.value})} className="mt-1 w-full border border-slate-200 rounded-lg p-2.5 bg-white"><option>Certified</option><option>Certified with Exception</option><option>Not Certified</option></select></label><button className="bg-brand-600 text-white font-bold px-4 py-2.5 rounded-lg">Record Certification</button></form>
   <form onSubmit={attest} className="bg-white border border-slate-200 rounded-xl p-5 space-y-3 text-xs"><h2 className="text-sm font-bold text-slate-900">Management Attestation</h2><label className="font-semibold text-slate-700 block">Period<input required value={attForm.period} onChange={e=>setAttForm({...attForm,period:e.target.value})} className="mt-1 w-full border border-slate-200 rounded-lg p-2.5"/></label><label className="font-semibold text-slate-700 block">Scope summary<textarea required value={attForm.scopeSummary} onChange={e=>setAttForm({...attForm,scopeSummary:e.target.value})} rows={3} className="mt-1 w-full border border-slate-200 rounded-lg p-2.5"/></label><label className="font-semibold text-slate-700 block">Overall opinion<textarea required value={attForm.overallOpinion} onChange={e=>setAttForm({...attForm,overallOpinion:e.target.value})} rows={3} className="mt-1 w-full border border-slate-200 rounded-lg p-2.5"/></label><div className="flex gap-4"><label className="flex items-center gap-2"><input type="checkbox" checked={attForm.cfoSignOff} onChange={e=>setAttForm({...attForm,cfoSignOff:e.target.checked})}/>CFO sign-off by current actor</label><label className="flex items-center gap-2"><input type="checkbox" checked={attForm.croSignOff} onChange={e=>setAttForm({...attForm,croSignOff:e.target.checked})}/>CRO sign-off</label></div><label className="font-semibold text-slate-700 block">CRO name (when applicable)<input value={attForm.croName} onChange={e=>setAttForm({...attForm,croName:e.target.value})} className="mt-1 w-full border border-slate-200 rounded-lg p-2.5"/></label><button className="bg-slate-900 text-white font-bold px-4 py-2.5 rounded-lg">Record Attestation</button></form>
  </div>
  <div className="grid xl:grid-cols-2 gap-5"><section className="bg-white border border-slate-200 rounded-xl p-5"><h2 className="text-sm font-bold text-slate-900 mb-3">Control Certifications</h2><div className="space-y-3">{certs.map(c=><div key={c.id} className="border border-slate-100 rounded-lg p-3"><div className="flex justify-between"><span className="text-xs font-bold">{c.control.controlId} — {c.period}</span><span className="text-[10px] bg-slate-100 px-2 py-1 rounded">{c.status}</span></div><div className="text-[11px] text-slate-500 mt-1">{c.certifierName} • {c.certifierRole} • {new Date(c.certifiedAt).toLocaleString('id-ID')}</div><p className="text-[11px] text-slate-700 mt-2">{c.declarationText}</p></div>)}{!certs.length&&<div className="text-xs text-slate-400">No certification recorded.</div>}</div></section><section className="bg-white border border-slate-200 rounded-xl p-5"><h2 className="text-sm font-bold text-slate-900 mb-3">Management Attestations</h2><div className="space-y-3">{atts.map(a=><div key={a.id} className="border border-slate-100 rounded-lg p-3"><div className="text-xs font-bold">{a.period}</div><div className="text-[11px] text-slate-500 mt-1">{a.attestedAt?new Date(a.attestedAt).toLocaleString('id-ID'):'Not attested'}</div><p className="text-[11px] text-slate-700 mt-2">{a.overallOpinion||'No opinion recorded.'}</p></div>)}{!atts.length&&<div className="text-xs text-slate-400">No management attestation recorded.</div>}</div></section></div>
 </div>;
}
