'use client';

import React, { useEffect, useMemo, useState } from 'react';
import { AlertCircle, CheckCircle2, FileOutput, Pencil, Plus, Save, Sheet } from 'lucide-react';

type Item={id:string;artifactType:'IPE'|'EUC';itemCode:string;name:string;sourceSystem?:string|null;owner:string;purpose:string;frequency?:string|null;logicDescription?:string|null;parameters?:string|null;dataSource?:string|null;completenessMethod?:string|null;accuracyMethod?:string|null;accessRestricted:boolean;versionControlled:boolean;keyReport:boolean;status:string};
const blank={id:'',artifactType:'IPE',itemCode:'',name:'',sourceSystem:'',owner:'',purpose:'',frequency:'',logicDescription:'',parameters:'',dataSource:'',completenessMethod:'',accuracyMethod:'',accessRestricted:false,versionControlled:false,keyReport:false,status:'Draft'};

export default function Page(){
 const [records,setRecords]=useState<Item[]>([]); const [institution,setInstitution]=useState<any>(null); const [form,setForm]=useState<any>(blank); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('');
 useEffect(()=>{let active=true;fetch('/api/icofr/information',{cache:'no-store'}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||'Register unavailable');return b}).then(b=>{if(active){setRecords(b.records||[]);setInstitution(b.institution||null)}}).catch(e=>active&&setError(e instanceof Error?e.message:'Register unavailable')).finally(()=>active&&setLoading(false));return()=>{active=false}},[]);
 const counts=useMemo(()=>({ipe:records.filter(x=>x.artifactType==='IPE').length,euc:records.filter(x=>x.artifactType==='EUC').length,key:records.filter(x=>x.keyReport).length}),[records]);
 const reset=()=>{setForm(blank);setError('');setMessage('')};
 const edit=(x:Item)=>{setForm({...blank,...x});setMessage('');window.scrollTo({top:0,behavior:'smooth'})};
 const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');setMessage('');try{const r=await fetch('/api/icofr/information',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const b=await r.json();if(!r.ok)throw new Error(b.error||'Save failed');setRecords(cur=>cur.some(x=>x.id===b.id)?cur.map(x=>x.id===b.id?b:x):[...cur,b].sort((a,c)=>a.itemCode.localeCompare(c.itemCode)));setForm((f:any)=>({...f,id:b.id}));setMessage(form.id?'Record updated in Cloudflare D1.':'Record saved in Cloudflare D1.')}catch(e){setError(e instanceof Error?e.message:'Save failed')}finally{setSaving(false)}};
 return <div className="space-y-5">
  <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.12em] text-sky-600"><FileOutput className="h-4 w-4"/>ICOFR · Information Reliability</div><h1 className="mt-1 text-2xl font-black text-slate-900">IPE & EUC Register</h1><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-500">Maintain Information Produced by the Entity (IPE) and End-User Computing (EUC) artifacts used by key controls, including completeness, accuracy, access and version-control evidence.</p></div><div className="flex gap-2 text-[10px] font-bold"><span className="rounded-full bg-sky-50 px-3 py-1 text-sky-700">IPE {counts.ipe}</span><span className="rounded-full bg-indigo-50 px-3 py-1 text-indigo-700">EUC {counts.euc}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-slate-600">Key {counts.key}</span></div></div></div>
  {error&&<div className="flex gap-2 rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs text-rose-700"><AlertCircle className="h-4 w-4"/>{error}</div>}
  {message&&<div className="flex gap-2 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs text-emerald-700"><CheckCircle2 className="h-4 w-4"/>{message}</div>}
  {!loading&&!institution?<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-xs text-slate-500">Register an institution before maintaining IPE/EUC.</div>:
  <form onSubmit={save} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
   <div className="mb-4 flex items-center justify-between"><div><h2 className="text-sm font-black text-slate-900">{form.id?'Edit information artifact':'Register information artifact'}</h2><p className="text-[10px] text-slate-500">No sample records are preloaded.</p></div>{form.id&&<button type="button" onClick={reset} className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-3 py-1.5 text-[10px] font-bold"><Plus className="h-3 w-3"/>New</button>}</div>
   <div className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3">
    <label className="text-xs font-bold text-slate-700">Type *<select required value={form.artifactType} onChange={e=>setForm({...form,artifactType:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"><option>IPE</option><option>EUC</option></select></label>
    <label className="text-xs font-bold text-slate-700">Code *<input required value={form.itemCode} onChange={e=>setForm({...form,itemCode:e.target.value})} placeholder={form.artifactType+'-001'} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="text-xs font-bold text-slate-700">Name *<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="text-xs font-bold text-slate-700">Source system / tool<input value={form.sourceSystem} onChange={e=>setForm({...form,sourceSystem:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="text-xs font-bold text-slate-700">Owner *<input required value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="text-xs font-bold text-slate-700">Frequency<input value={form.frequency} onChange={e=>setForm({...form,frequency:e.target.value})} placeholder="Daily / Monthly / On demand" className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="text-xs font-bold text-slate-700 md:col-span-2 xl:col-span-3">Purpose *<textarea required rows={2} value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="text-xs font-bold text-slate-700">Data source<input value={form.dataSource} onChange={e=>setForm({...form,dataSource:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="text-xs font-bold text-slate-700">Parameters / filters<input value={form.parameters} onChange={e=>setForm({...form,parameters:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="text-xs font-bold text-slate-700">Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"><option>Draft</option><option>Validated</option><option>Approved</option><option>Retired</option></select></label>
    <label className="text-xs font-bold text-slate-700 md:col-span-2 xl:col-span-3">Logic / report generation description<textarea rows={2} value={form.logicDescription} onChange={e=>setForm({...form,logicDescription:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="text-xs font-bold text-slate-700">Completeness validation method<textarea rows={2} value={form.completenessMethod} onChange={e=>setForm({...form,completenessMethod:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="text-xs font-bold text-slate-700">Accuracy validation method<textarea rows={2} value={form.accuracyMethod} onChange={e=>setForm({...form,accuracyMethod:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <div className="flex flex-col gap-2 rounded-xl border border-slate-200 p-3 text-xs font-bold text-slate-700"><label className="flex items-center gap-2"><input type="checkbox" checked={form.keyReport} onChange={e=>setForm({...form,keyReport:e.target.checked})}/>Key report / key EUC</label><label className="flex items-center gap-2"><input type="checkbox" checked={form.accessRestricted} onChange={e=>setForm({...form,accessRestricted:e.target.checked})}/>Access restricted</label><label className="flex items-center gap-2"><input type="checkbox" checked={form.versionControlled} onChange={e=>setForm({...form,versionControlled:e.target.checked})}/>Version controlled</label></div>
   </div>
   <div className="mt-4 flex justify-end"><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-brand-600 px-5 py-2.5 text-xs font-black text-white disabled:opacity-50"><Save className="h-4 w-4"/>{saving?'Saving…':form.id?'Update Record':'Save Record'}</button></div>
  </form>}
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-3 text-sm font-black text-slate-900">IPE / EUC inventory</h2>{loading?<div className="py-8 text-center text-xs text-slate-500">Loading…</div>:records.length===0?<div className="rounded-xl border border-dashed border-slate-300 p-8 text-center text-xs text-slate-500">No IPE or EUC records registered.</div>:<div className="space-y-2">{records.map(x=><div key={x.id} className="rounded-xl border border-slate-200 p-3"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="font-mono text-[10px] font-black text-brand-700">{x.itemCode}</span><span className="rounded-full bg-slate-100 px-2 py-0.5 text-[9px] font-bold">{x.artifactType}</span>{x.keyReport&&<span className="rounded-full bg-sky-50 px-2 py-0.5 text-[9px] font-bold text-sky-700">Key</span>}</div><div className="mt-1 text-sm font-bold text-slate-900">{x.name}</div><div className="mt-1 text-[10px] text-slate-500">{[x.sourceSystem,x.owner,x.status].filter(Boolean).join(' · ')}</div></div><button onClick={()=>edit(x)} className="rounded-lg border border-slate-200 p-2 text-slate-500"><Pencil className="h-3.5 w-3.5"/></button></div></div>)}</div>}</section>
 </div>
}
