'use client';

import React, { useEffect, useMemo, useState } from 'react';
import { AlertCircle, CheckCircle2, CircleAlert, Pencil, Plus, Save } from 'lucide-react';

type Item={id:string;deficiencyCode:string;title:string;controlDomain?:string|null;controlReference?:string|null;description:string;financialStatementImpact?:string|null;likelihood?:string|null;severity:string;aggregationConsidered:boolean;compensatingControls?:string|null;conclusion?:string|null;owner:string;dueDate?:string|null;status:string};
const blank={id:'',deficiencyCode:'',title:'',controlDomain:'',controlReference:'',description:'',financialStatementImpact:'',likelihood:'',severity:'',aggregationConsidered:false,compensatingControls:'',conclusion:'',owner:'',dueDate:'',status:'Open'};

function severityLabel(value:string){
 if(value==='Control Deficiency') return 'Defisiensi Pengendalian';
 if(value==='Significant Deficiency') return 'Defisiensi Signifikan';
 if(value==='Material Weakness') return 'Kelemahan Material';
 return value;
}
function statusLabel(value:string){
 if(value==='Open') return 'Terbuka';
 if(value==='Remediation In Progress') return 'Remediasi Berjalan';
 if(value==='Pending Retest') return 'Menunggu Pengujian Ulang';
 if(value==='Closed') return 'Ditutup';
 return value;
}

export default function Page(){
 const [records,setRecords]=useState<Item[]>([]); const [institution,setInstitution]=useState<any>(null); const [form,setForm]=useState<any>(blank); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('');
 useEffect(()=>{let active=true;fetch('/api/icofr/deficiencies',{cache:'no-store'}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||'Register defisiensi tidak tersedia');return b}).then(b=>{if(active){setRecords(b.records||[]);setInstitution(b.institution||null)}}).catch(e=>active&&setError(e instanceof Error?e.message:'Register defisiensi tidak tersedia')).finally(()=>active&&setLoading(false));return()=>{active=false}},[]);
 const stats=useMemo(()=>({open:records.filter(x=>x.status!=='Closed').length,material:records.filter(x=>x.severity==='Material Weakness').length,significant:records.filter(x=>x.severity==='Significant Deficiency').length}),[records]);
 const reset=()=>{setForm(blank);setError('');setMessage('')};
 const edit=(x:Item)=>{setForm({...blank,...x,dueDate:x.dueDate||''});setMessage('');window.scrollTo({top:0,behavior:'smooth'})};
 const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');setMessage('');try{const r=await fetch('/api/icofr/deficiencies',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const b=await r.json();if(!r.ok)throw new Error(b.error||'Gagal menyimpan defisiensi');setRecords(cur=>cur.some(x=>x.id===b.id)?cur.map(x=>x.id===b.id?b:x):[b,...cur]);setForm((f:any)=>({...f,id:b.id}));setMessage(form.id?'Defisiensi berhasil diperbarui di Cloudflare D1.':'Defisiensi berhasil disimpan di Cloudflare D1.')}catch(e){setError(e instanceof Error?e.message:'Gagal menyimpan defisiensi')}finally{setSaving(false)}};
 return <div className="space-y-5">
  <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.12em] text-sky-600"><CircleAlert className="h-4 w-4"/>ICOFR · Evaluasi Defisiensi</div><h1 className="mt-1 text-2xl font-black text-slate-900">Evaluasi Defisiensi ICOFR</h1><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-500">Evaluasi defisiensi pengendalian secara individual maupun agregat, dokumentasikan dampaknya terhadap laporan keuangan, pengendalian kompensasi, serta kesimpulan manajemen sebelum proses remediasi dan sertifikasi.</p></div><div className="flex gap-2 text-[10px] font-bold"><span className="rounded-full bg-slate-100 px-3 py-1 text-slate-600">Terbuka {stats.open}</span><span className="rounded-full bg-amber-50 px-3 py-1 text-amber-700">Signifikan {stats.significant}</span><span className="rounded-full bg-rose-50 px-3 py-1 text-rose-700">Material {stats.material}</span></div></div></div>
  {error&&<div className="flex gap-2 rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs text-rose-700"><AlertCircle className="h-4 w-4"/>{error}</div>}
  {message&&<div className="flex gap-2 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs text-emerald-700"><CheckCircle2 className="h-4 w-4"/>{message}</div>}
  {!loading&&!institution?<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-xs text-slate-500">Daftarkan institusi terlebih dahulu sebelum mengelola defisiensi ICOFR.</div>:
  <form onSubmit={save} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
   <div className="mb-4 flex items-center justify-between"><div><h2 className="text-sm font-black text-slate-900">{form.id?'Ubah defisiensi':'Daftarkan defisiensi'}</h2><p className="text-[10px] text-slate-500">Tingkat keparahan merupakan kesimpulan yang didokumentasikan oleh manajemen/reviewer, bukan hasil penetapan otomatis.</p></div>{form.id&&<button type="button" onClick={reset} className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-3 py-1.5 text-[10px] font-bold"><Plus className="h-3 w-3"/>Baru</button>}</div>
   <div className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3">
    <label className="text-xs font-bold text-slate-700">Kode defisiensi *<input required value={form.deficiencyCode} onChange={e=>setForm({...form,deficiencyCode:e.target.value})} placeholder="DEF-001" className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="text-xs font-bold text-slate-700 md:col-span-2">Judul *<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="text-xs font-bold text-slate-700">Domain pengendalian<select value={form.controlDomain} onChange={e=>setForm({...form,controlDomain:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"><option value="">Pilih</option><option>ELC</option><option>PLC</option><option>ITGC</option><option>ITAC</option><option>IPE</option><option>EUC</option></select></label>
    <label className="text-xs font-bold text-slate-700">Referensi pengendalian<input value={form.controlReference} onChange={e=>setForm({...form,controlReference:e.target.value})} placeholder="ID kontrol / referensi pengujian" className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="text-xs font-bold text-slate-700">Penanggung jawab *<input required value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="text-xs font-bold text-slate-700 md:col-span-2 xl:col-span-3">Deskripsi defisiensi *<textarea required rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="text-xs font-bold text-slate-700 md:col-span-2">Dampak terhadap laporan keuangan<textarea rows={2} value={form.financialStatementImpact} onChange={e=>setForm({...form,financialStatementImpact:e.target.value})} placeholder="Akun, pengungkapan, asersi, besaran, atau potensi salah saji yang terdampak." className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="text-xs font-bold text-slate-700">Kemungkinan terjadinya<select value={form.likelihood} onChange={e=>setForm({...form,likelihood:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"><option value="">Pilih</option><option value="Remote">Rendah / kecil kemungkinan</option><option value="Reasonably Possible">Mungkin terjadi</option><option value="Probable">Kemungkinan besar</option></select></label>
    <label className="text-xs font-bold text-slate-700">Tingkat keparahan *<select required value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"><option value="">Pilih</option><option value="Control Deficiency">Defisiensi Pengendalian</option><option value="Significant Deficiency">Defisiensi Signifikan</option><option value="Material Weakness">Kelemahan Material</option></select></label>
    <label className="text-xs font-bold text-slate-700">Batas waktu<input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="text-xs font-bold text-slate-700">Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"><option value="Open">Terbuka</option><option value="Remediation In Progress">Remediasi Berjalan</option><option value="Pending Retest">Menunggu Pengujian Ulang</option><option value="Closed">Ditutup</option></select></label>
    <label className="text-xs font-bold text-slate-700 md:col-span-2">Pengendalian kompensasi<textarea rows={2} value={form.compensatingControls} onChange={e=>setForm({...form,compensatingControls:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="text-xs font-bold text-slate-700">Kesimpulan manajemen / reviewer<textarea rows={2} value={form.conclusion} onChange={e=>setForm({...form,conclusion:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="flex items-center gap-2 self-end rounded-xl border border-slate-200 px-3 py-2.5 text-xs font-bold text-slate-700"><input type="checkbox" checked={form.aggregationConsidered} onChange={e=>setForm({...form,aggregationConsidered:e.target.checked})}/>Agregasi dengan defisiensi lain telah dipertimbangkan</label>
   </div>
   <div className="mt-4 flex justify-end"><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-brand-600 px-5 py-2.5 text-xs font-black text-white disabled:opacity-50"><Save className="h-4 w-4"/>{saving?'Menyimpan…':form.id?'Perbarui Defisiensi':'Simpan Defisiensi'}</button></div>
  </form>}
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-3 text-sm font-black text-slate-900">Register defisiensi</h2>{loading?<div className="py-8 text-center text-xs text-slate-500">Memuat…</div>:records.length===0?<div className="rounded-xl border border-dashed border-slate-300 p-8 text-center text-xs text-slate-500">Belum ada defisiensi ICOFR yang terdaftar.</div>:<div className="space-y-2">{records.map(x=><div key={x.id} className="rounded-xl border border-slate-200 p-3"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-[10px] font-black text-brand-700">{x.deficiencyCode}</span><span className={"rounded-full px-2 py-0.5 text-[9px] font-bold "+(x.severity==='Material Weakness'?'bg-rose-50 text-rose-700':x.severity==='Significant Deficiency'?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-600')}>{severityLabel(x.severity)}</span><span className="rounded-full bg-slate-100 px-2 py-0.5 text-[9px] font-bold">{statusLabel(x.status)}</span></div><div className="mt-1 text-sm font-bold text-slate-900">{x.title}</div><div className="mt-1 text-[10px] text-slate-500">{[x.controlDomain,x.controlReference,x.owner].filter(Boolean).join(' · ')}</div></div><button onClick={()=>edit(x)} className="rounded-lg border border-slate-200 p-2 text-slate-500"><Pencil className="h-3.5 w-3.5"/></button></div></div>)}</div>}</section>
 </div>
}
