'use client';

import React, { useEffect, useMemo, useState } from 'react';
import { AlertCircle, CheckCircle2, CircleAlert, Pencil, Plus, Save } from 'lucide-react';

type Item={id:string;deficiencyCode:string;title:string;controlDomain?:string|null;controlReference?:string|null;description:string;financialStatementImpact?:string|null;likelihood?:string|null;severity:string;aggregationConsidered:boolean;compensatingControls?:string|null;conclusion?:string|null;owner:string;dueDate?:string|null;status:string};
const blank={id:'',deficiencyCode:'',title:'',controlDomain:'',controlReference:'',description:'',financialStatementImpact:'',likelihood:'',severity:'',aggregationConsidered:false,compensatingControls:'',conclusion:'',owner:'',dueDate:'',status:'Open'};

export default function Page(){
 const [records,setRecords]=useState<Item[]>([]); const [institution,setInstitution]=useState<any>(null); const [form,setForm]=useState<any>(blank); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('');
 useEffect(()=>{let active=true;fetch('/api/icofr/deficiencies',{cache:'no-store'}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||'Register unavailable');return b}).then(b=>{if(active){setRecords(b.records||[]);setInstitution(b.institution||null)}}).catch(e=>active&&setError(e instanceof Error?e.message:'Register unavailable')).finally(()=>active&&setLoading(false));return()=>{active=false}},[]);
 const stats=useMemo(()=>({open:records.filter(x=>x.status!=='Closed').length,material:records.filter(x=>x.severity==='Material Weakness').length,significant:records.filter(x=>x.severity==='Significant Deficiency').length}),[records]);
 const reset=()=>{setForm(blank);setError('');setMessage('')};
 const edit=(x:Item)=>{setForm({...blank,...x,dueDate:x.dueDate||''});setMessage('');window.scrollTo({top:0,behavior:'smooth'})};
 const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');setMessage('');try{const r=await fetch('/api/icofr/deficiencies',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const b=await r.json();if(!r.ok)throw new Error(b.error||'Save failed');setRecords(cur=>cur.some(x=>x.id===b.id)?cur.map(x=>x.id===b.id?b:x):[b,...cur]);setForm((f:any)=>({...f,id:b.id}));setMessage(form.id?'Deficiency updated in Cloudflare D1.':'Deficiency saved in Cloudflare D1.')}catch(e){setError(e instanceof Error?e.message:'Save failed')}finally{setSaving(false)}};
 return <div className="space-y-5">
  <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.12em] text-sky-600"><CircleAlert className="h-4 w-4"/>ICOFR · Deficiency Evaluation</div><h1 className="mt-1 text-2xl font-black text-slate-900">ICOFR Deficiency Evaluation</h1><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-500">Evaluate control deficiencies individually and in aggregate, document financial statement impact, compensating controls and management conclusion before remediation and certification.</p></div><div className="flex gap-2 text-[10px] font-bold"><span className="rounded-full bg-slate-100 px-3 py-1 text-slate-600">Open {stats.open}</span><span className="rounded-full bg-amber-50 px-3 py-1 text-amber-700">Significant {stats.significant}</span><span className="rounded-full bg-rose-50 px-3 py-1 text-rose-700">Material {stats.material}</span></div></div></div>
  {error&&<div className="flex gap-2 rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs text-rose-700"><AlertCircle className="h-4 w-4"/>{error}</div>}
  {message&&<div className="flex gap-2 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs text-emerald-700"><CheckCircle2 className="h-4 w-4"/>{message}</div>}
  {!loading&&!institution?<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-xs text-slate-500">Register an institution before maintaining ICOFR deficiencies.</div>:
  <form onSubmit={save} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
   <div className="mb-4 flex items-center justify-between"><div><h2 className="text-sm font-black text-slate-900">{form.id?'Edit deficiency':'Register deficiency'}</h2><p className="text-[10px] text-slate-500">Severity is a documented management/reviewer conclusion, not automatically inferred.</p></div>{form.id&&<button type="button" onClick={reset} className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-3 py-1.5 text-[10px] font-bold"><Plus className="h-3 w-3"/>New</button>}</div>
   <div className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3">
    <label className="text-xs font-bold text-slate-700">Deficiency code *<input required value={form.deficiencyCode} onChange={e=>setForm({...form,deficiencyCode:e.target.value})} placeholder="DEF-001" className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="text-xs font-bold text-slate-700 md:col-span-2">Title *<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="text-xs font-bold text-slate-700">Control domain<select value={form.controlDomain} onChange={e=>setForm({...form,controlDomain:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"><option value="">Select</option><option>ELC</option><option>PLC</option><option>ITGC</option><option>ITAC</option><option>IPE</option><option>EUC</option></select></label>
    <label className="text-xs font-bold text-slate-700">Control reference<input value={form.controlReference} onChange={e=>setForm({...form,controlReference:e.target.value})} placeholder="Control ID / test reference" className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="text-xs font-bold text-slate-700">Owner *<input required value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="text-xs font-bold text-slate-700 md:col-span-2 xl:col-span-3">Deficiency description *<textarea required rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="text-xs font-bold text-slate-700 md:col-span-2">Financial statement impact<textarea rows={2} value={form.financialStatementImpact} onChange={e=>setForm({...form,financialStatementImpact:e.target.value})} placeholder="Affected accounts, disclosures, assertions, magnitude or possible misstatement." className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="text-xs font-bold text-slate-700">Likelihood<select value={form.likelihood} onChange={e=>setForm({...form,likelihood:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"><option value="">Select</option><option>Remote</option><option>Reasonably Possible</option><option>Probable</option></select></label>
    <label className="text-xs font-bold text-slate-700">Severity *<select required value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"><option value="">Select</option><option>Control Deficiency</option><option>Significant Deficiency</option><option>Material Weakness</option></select></label>
    <label className="text-xs font-bold text-slate-700">Due date<input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="text-xs font-bold text-slate-700">Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"><option>Open</option><option>Remediation In Progress</option><option>Pending Retest</option><option>Closed</option></select></label>
    <label className="text-xs font-bold text-slate-700 md:col-span-2">Compensating controls<textarea rows={2} value={form.compensatingControls} onChange={e=>setForm({...form,compensatingControls:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="text-xs font-bold text-slate-700">Management / reviewer conclusion<textarea rows={2} value={form.conclusion} onChange={e=>setForm({...form,conclusion:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>
    <label className="flex items-center gap-2 self-end rounded-xl border border-slate-200 px-3 py-2.5 text-xs font-bold text-slate-700"><input type="checkbox" checked={form.aggregationConsidered} onChange={e=>setForm({...form,aggregationConsidered:e.target.checked})}/>Aggregation with other deficiencies considered</label>
   </div>
   <div className="mt-4 flex justify-end"><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-brand-600 px-5 py-2.5 text-xs font-black text-white disabled:opacity-50"><Save className="h-4 w-4"/>{saving?'Saving…':form.id?'Update Deficiency':'Save Deficiency'}</button></div>
  </form>}
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-3 text-sm font-black text-slate-900">Deficiency register</h2>{loading?<div className="py-8 text-center text-xs text-slate-500">Loading…</div>:records.length===0?<div className="rounded-xl border border-dashed border-slate-300 p-8 text-center text-xs text-slate-500">No ICOFR deficiencies registered.</div>:<div className="space-y-2">{records.map(x=><div key={x.id} className="rounded-xl border border-slate-200 p-3"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-[10px] font-black text-brand-700">{x.deficiencyCode}</span><span className={"rounded-full px-2 py-0.5 text-[9px] font-bold "+(x.severity==='Material Weakness'?'bg-rose-50 text-rose-700':x.severity==='Significant Deficiency'?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-600')}>{x.severity}</span><span className="rounded-full bg-slate-100 px-2 py-0.5 text-[9px] font-bold">{x.status}</span></div><div className="mt-1 text-sm font-bold text-slate-900">{x.title}</div><div className="mt-1 text-[10px] text-slate-500">{[x.controlDomain,x.controlReference,x.owner].filter(Boolean).join(' · ')}</div></div><button onClick={()=>edit(x)} className="rounded-lg border border-slate-200 p-2 text-slate-500"><Pencil className="h-3.5 w-3.5"/></button></div></div>)}</div>}</section>
 </div>
}
